services:
  api:
    container_name: "marketing-service-api"
    networks:
      - marketing
    build:
      context: ./api
      dockerfile: Dockerfile
    restart: unless-stopped
    ports:
      - "7057:7056"
    depends_on:
      postgres-db:
        condition: service_healthy
    environment:
      DB_URL: ${DB_URL:-jdbc:postgresql://postgres-db:5432/marketing-main?currentSchema=public}
      DB_PASSWORD: ${DB_PASSWORD}
      DB_USERNAME: ${DB_USERNAME}
      EMAIL_HOST: ${EMAIL_HOST:-mailpit}
      EMAIL_PORT: ${EMAIL_PORT:-1025}
      TEMPORAL_ADDRESS: ${TEMPORAL_ADDRESS:-temporal-server:7233}
      EMAIL_USERNAME: ${EMAIL_USERNAME:-testuser@gmail.com}
      EMAIL_FROM_ADDRESS: ${EMAIL_FROM_ADDRESS:-test@noreply.com}
      EMAIL_PASSWORD: ${EMAIL_PASSWORD:-testpwd}
      SERVER_PORT: 7056
      SERVER_ADDRESS: 0.0.0.0
  frontend:
    container_name: "marketing-frontend-ui"
    networks:
      - marketing
    platform: linux/arm64
    build:
      context: ./frontend
      dockerfile: Dockerfile
      args:
        NODE_BASE_IMAGE: node:22-alpine
    restart: unless-stopped
    ports:
      - "3000:3000"
    depends_on:
      api:
        condition: service_started
    environment:
      AUTH_MICROSOFT_ENTRA_ID_ID: ${AUTH_MICROSOFT_ENTRA_ID_ID}
      AUTH_MICROSOFT_ENTRA_ID_SECRET: ${AUTH_MICROSOFT_ENTRA_ID_SECRET}
      AUTH_MICROSOFT_ENTRA_ID_TENANT_ID: ${AUTH_MICROSOFT_ENTRA_ID_TENANT_ID}
      AUTH_MICROSOFT_ENTRA_ID_ISSUER: ${AUTH_MICROSOFT_ENTRA_ID_ISSUER}
      AUTH_MICROSOFT_ENTRA_ID_API_SCOPE: ${AUTH_MICROSOFT_ENTRA_ID_API_SCOPE}
      API_URL: http://api:7056
      AUTH_URL: http://localhost:3000
      AUTH_SECRET: ${AUTH_SECRET}
  notification-sender:
    container_name: "notification-sender"
    networks:
      - marketing
    build:
      context: ./workers/transactional-message-sender
      dockerfile: Dockerfile
    restart: unless-stopped
    depends_on:
      postgres-db:
        condition: service_healthy
    environment:
      DB_URL: ${DB_URL:-postgres-db:5432/marketing-main?currentSchema=public}
      DB_PASSWORD: ${DB_PASSWORD}
      DB_USERNAME: ${DB_USERNAME}
      EMAIL_HOST: ${EMAIL_HOST:-mailpit}
      TEMPORAL_ADDRESS: ${TEMPORAL_ADDRESS:-temporal-server:7233}
      EMAIL_PORT: ${EMAIL_PORT:-1025}
      EMAIL_USERNAME: ${EMAIL_USERNAME:-testuser@gmail.com}
      EMAIL_FROM_ADDRESS: ${EMAIL_FROM_ADDRESS:-test@noreply.com}
      EMAIL_PASSWORD: ${EMAIL_PASSWORD:-testpwd}
  temporal-admin-tools:
    image: temporalio/admin-tools:1.30
    container_name: marketing-temporal-admin-tools
    environment:
      - SQL_PLUGIN=postgres
      - SQL_HOST=postgres-db
      - SQL_PORT=5432
      - SQL_USER=${DB_USERNAME}
      - SQL_PASSWORD=${DB_PASSWORD}
      - TEMPORAL_ADDRESS=temporal-server:7233
    depends_on:
      postgres-db:
        condition: service_healthy
  temporal-server:
    image: temporalio/auto-setup:1.29.7
    container_name: marketing-temporal-server
    networks:
      - marketing
    volumes:
      - ./dynamicconfig:/etc/temporal/config/dynamicconfig
    environment:
      DB: postgres12
      DB_PORT: 5432
      POSTGRES_SEEDS: postgres-db
      POSTGRES_USER: ${DB_USERNAME}
      POSTGRES_PWD: ${DB_PASSWORD}
      ENABLE_ES: "false"
      # Fixed to use the absolute path matching the volume mount
      DYNAMIC_CONFIG_FILE_PATH: /etc/temporal/config/dynamicconfig/development.yaml
      TEMPORAL_ADDRESS: temporal-server:7233

    depends_on:
      postgres-db:
        condition: service_healthy
  temporal-ui:
    image: temporalio/ui:2.52.0
    networks:
      - marketing
    ports:
      - "8444:8080"
    environment:
      TEMPORAL_ADDRESS: temporal-server:7233
    depends_on:
      - temporal-server
  mailpit:
    image: axllent/mailpit:latest
    container_name: mailpit
    restart: unless-stopped
    networks:
      - marketing
    volumes:
      - ./mailpit-data:/data
    ports:
      - "6025:8025" # Web U
    environment:
      MP_MAX_MESSAGES: 5000
      MP_DATABASE: /data/mailpit.db
      MP_SMTP_AUTH_ACCEPT_ANY: 1
      MP_SMTP_AUTH_ALLOW_INSECURE: 1
  postgres-db:
    container_name: postgres-db
    image: postgres:15.3-alpine
    networks:
      - marketing
    ports:
      - "5435:5432"
    environment:
      POSTGRES_DB: marketing-main
      POSTGRES_USER: ${DB_USERNAME}
      POSTGRES_PASSWORD: ${DB_PASSWORD}
      PGDATA: /var/lib/postgresql/data/pgdata
    volumes:
      - postgres_data:/var/lib/postgresql/data
      - ./sql/init.sql:/docker-entrypoint-initdb.d/init.sql:ro
    restart: unless-stopped
    healthcheck:
      test: [ "CMD-SHELL", "pg_isready -U ${DB_USERNAME:-postgres} -d marketing-main" ]
      interval: 30s
      timeout: 10s
      retries: 3
networks:
  marketing:
    driver: bridge
    name: marketing
volumes:
  postgres_data:
    driver: local