/*
 * This file is generated by jOOQ.
 */
package com.ogoma.marketing.infrastructure.jooq.tables;


import com.ogoma.marketing.infrastructure.jooq.DefaultSchema;
import com.ogoma.marketing.infrastructure.jooq.Keys;
import com.ogoma.marketing.infrastructure.jooq.tables.CampaignAudience.CampaignAudiencePath;
import com.ogoma.marketing.infrastructure.jooq.tables.Campaigns.CampaignsPath;
import com.ogoma.marketing.infrastructure.jooq.tables.records.AudiencesRecord;
import org.jooq.*;
import org.jooq.Record;
import org.jooq.impl.DSL;
import org.jooq.impl.Internal;
import org.jooq.impl.SQLDataType;
import org.jooq.impl.TableImpl;

import java.time.OffsetDateTime;
import java.util.Collection;
import java.util.UUID;


/**
 * This class is generated by jOOQ.
 */
@SuppressWarnings({ "all", "unchecked", "rawtypes", "this-escape" })
public class Audiences extends TableImpl<AudiencesRecord> {

    private static final long serialVersionUID = 1L;

    /**
     * The reference instance of <code>audiences</code>
     */
    public static final Audiences AUDIENCES = new Audiences();

    /**
     * The class holding records for this type
     */
    @Override
    public Class<AudiencesRecord> getRecordType() {
        return AudiencesRecord.class;
    }

    /**
     * The column <code>audiences.id</code>.
     */
    public final TableField<AudiencesRecord, UUID> ID = createField(DSL.name("id"), SQLDataType.UUID.nullable(false), this, "");

    /**
     * The column <code>audiences.name</code>.
     */
    public final TableField<AudiencesRecord, String> NAME = createField(DSL.name("name"), SQLDataType.VARCHAR.nullable(false), this, "");

    /**
     * The column <code>audiences.version</code>.
     */
    public final TableField<AudiencesRecord, Long> VERSION = createField(DSL.name("version"), SQLDataType.BIGINT.nullable(false), this, "");

    /**
     * The column <code>audiences.created_at</code>.
     */
    public final TableField<AudiencesRecord, OffsetDateTime> CREATED_AT = createField(DSL.name("created_at"), SQLDataType.TIMESTAMPWITHTIMEZONE(6).nullable(false), this, "");

    /**
     * The column <code>audiences.updated_at</code>.
     */
    public final TableField<AudiencesRecord, OffsetDateTime> UPDATED_AT = createField(DSL.name("updated_at"), SQLDataType.TIMESTAMPWITHTIMEZONE(6).nullable(false), this, "");

    /**
     * The column <code>audiences.created_by</code>.
     */
    public final TableField<AudiencesRecord, String> CREATED_BY = createField(DSL.name("created_by"), SQLDataType.VARCHAR, this, "");

    /**
     * The column <code>audiences.updated_by</code>.
     */
    public final TableField<AudiencesRecord, String> UPDATED_BY = createField(DSL.name("updated_by"), SQLDataType.VARCHAR, this, "");

    /**
     * The column <code>audiences.type</code>.
     */
    public final TableField<AudiencesRecord, String> TYPE = createField(DSL.name("type"), SQLDataType.VARCHAR, this, "");

    /**
     * The column <code>audiences.ruleset</code>.
     */
    public final TableField<AudiencesRecord, JSONB> RULESET = createField(DSL.name("ruleset"), SQLDataType.JSONB, this, "");

    private Audiences(Name alias, Table<AudiencesRecord> aliased) {
        this(alias, aliased, (Field<?>[]) null, null);
    }

    private Audiences(Name alias, Table<AudiencesRecord> aliased, Field<?>[] parameters, Condition where) {
        super(alias, null, aliased, parameters, DSL.comment(""), TableOptions.table(), where);
    }

    /**
     * Create an aliased <code>audiences</code> table reference
     */
    public Audiences(String alias) {
        this(DSL.name(alias), AUDIENCES);
    }

    /**
     * Create an aliased <code>audiences</code> table reference
     */
    public Audiences(Name alias) {
        this(alias, AUDIENCES);
    }

    /**
     * Create a <code>audiences</code> table reference
     */
    public Audiences() {
        this(DSL.name("audiences"), null);
    }

    public <O extends Record> Audiences(Table<O> path, ForeignKey<O, AudiencesRecord> childPath, InverseForeignKey<O, AudiencesRecord> parentPath) {
        super(path, childPath, parentPath, AUDIENCES);
    }

    /**
     * A subtype implementing {@link Path} for simplified path-based joins.
     */
    public static class AudiencesPath extends Audiences implements Path<AudiencesRecord> {

        private static final long serialVersionUID = 1L;
        public <O extends Record> AudiencesPath(Table<O> path, ForeignKey<O, AudiencesRecord> childPath, InverseForeignKey<O, AudiencesRecord> parentPath) {
            super(path, childPath, parentPath);
        }
        private AudiencesPath(Name alias, Table<AudiencesRecord> aliased) {
            super(alias, aliased);
        }

        @Override
        public AudiencesPath as(String alias) {
            return new AudiencesPath(DSL.name(alias), this);
        }

        @Override
        public AudiencesPath as(Name alias) {
            return new AudiencesPath(alias, this);
        }

        @Override
        public AudiencesPath as(Table<?> alias) {
            return new AudiencesPath(alias.getQualifiedName(), this);
        }
    }

    @Override
    public Schema getSchema() {
        return aliased() ? null : DefaultSchema.DEFAULT_SCHEMA;
    }

    @Override
    public UniqueKey<AudiencesRecord> getPrimaryKey() {
        return Keys.AUDIENCES_PKEY;
    }

    private transient CampaignAudiencePath _campaignAudience;

    /**
     * Get the implicit to-many join path to the <code>campaign_audience</code>
     * table
     */
    public CampaignAudiencePath campaignAudience() {
        if (_campaignAudience == null)
            _campaignAudience = new CampaignAudiencePath(this, null, Keys.CAMPAIGN_AUDIENCE__CAMPAIGN_AUDIENCE_AUDIENCE_ID_FKEY.getInverseKey());

        return _campaignAudience;
    }

    /**
     * Get the implicit many-to-many join path to the <code>campaigns</code>
     * table
     */
    public CampaignsPath campaigns() {
        return campaignAudience().campaigns();
    }

    @Override
    public Audiences as(String alias) {
        return new Audiences(DSL.name(alias), this);
    }

    @Override
    public Audiences as(Name alias) {
        return new Audiences(alias, this);
    }

    @Override
    public Audiences as(Table<?> alias) {
        return new Audiences(alias.getQualifiedName(), this);
    }

    /**
     * Rename this table
     */
    @Override
    public Audiences rename(String name) {
        return new Audiences(DSL.name(name), null);
    }

    /**
     * Rename this table
     */
    @Override
    public Audiences rename(Name name) {
        return new Audiences(name, null);
    }

    /**
     * Rename this table
     */
    @Override
    public Audiences rename(Table<?> name) {
        return new Audiences(name.getQualifiedName(), null);
    }

    /**
     * Create an inline derived table from this table
     */
    @Override
    public Audiences where(Condition condition) {
        return new Audiences(getQualifiedName(), aliased() ? this : null, null, Internal.condition(this, condition));
    }

    /**
     * Create an inline derived table from this table
     */
    @Override
    public Audiences where(Collection<? extends Condition> conditions) {
        return where(DSL.and(conditions));
    }

    /**
     * Create an inline derived table from this table
     */
    @Override
    public Audiences where(Condition... conditions) {
        return where(DSL.and(conditions));
    }

    /**
     * Create an inline derived table from this table
     */
    @Override
    public Audiences where(Field<Boolean> condition) {
        return where(DSL.condition(condition));
    }

    /**
     * Create an inline derived table from this table
     */
    @Override
    @PlainSQL
    public Audiences where(SQL condition) {
        return where(DSL.condition(condition));
    }

    /**
     * Create an inline derived table from this table
     */
    @Override
    @PlainSQL
    public Audiences where(@Stringly.SQL String condition) {
        return where(DSL.condition(condition));
    }

    /**
     * Create an inline derived table from this table
     */
    @Override
    @PlainSQL
    public Audiences where(@Stringly.SQL String condition, Object... binds) {
        return where(DSL.condition(condition, binds));
    }

    /**
     * Create an inline derived table from this table
     */
    @Override
    @PlainSQL
    public Audiences where(@Stringly.SQL String condition, QueryPart... parts) {
        return where(DSL.condition(condition, parts));
    }

    /**
     * Create an inline derived table from this table
     */
    @Override
    public Audiences whereExists(TableLike<?> select) {
        return where(DSL.exists(select));
    }

    /**
     * Create an inline derived table from this table
     */
    @Override
    public Audiences whereNotExists(TableLike<?> select) {
        return where(DSL.notExists(select));
    }
}
