/*
 * This file is generated by jOOQ.
 */
package com.ogoma.marketing.infrastructure.jooq.tables;


import com.ogoma.marketing.infrastructure.jooq.DefaultSchema;
import com.ogoma.marketing.infrastructure.jooq.Keys;
import com.ogoma.marketing.infrastructure.jooq.tables.records.AudienceMembershipRecord;
import org.jooq.*;
import org.jooq.impl.DSL;
import org.jooq.impl.Internal;
import org.jooq.impl.SQLDataType;
import org.jooq.impl.TableImpl;

import java.time.OffsetDateTime;
import java.util.Collection;
import java.util.UUID;


/**
 * This class is generated by jOOQ.
 */
@SuppressWarnings({ "all", "unchecked", "rawtypes", "this-escape" })
public class AudienceMembership extends TableImpl<AudienceMembershipRecord> {

    private static final long serialVersionUID = 1L;

    /**
     * The reference instance of <code>audience_membership</code>
     */
    public static final AudienceMembership AUDIENCE_MEMBERSHIP = new AudienceMembership();

    /**
     * The class holding records for this type
     */
    @Override
    public Class<AudienceMembershipRecord> getRecordType() {
        return AudienceMembershipRecord.class;
    }

    /**
     * The column <code>audience_membership.id</code>.
     */
    public final TableField<AudienceMembershipRecord, UUID> ID = createField(DSL.name("id"), SQLDataType.UUID.nullable(false), this, "");

    /**
     * The column <code>audience_membership.contact_id</code>.
     */
    public final TableField<AudienceMembershipRecord, UUID> CONTACT_ID = createField(DSL.name("contact_id"), SQLDataType.UUID.nullable(false), this, "");

    /**
     * The column <code>audience_membership.audience_id</code>.
     */
    public final TableField<AudienceMembershipRecord, UUID> AUDIENCE_ID = createField(DSL.name("audience_id"), SQLDataType.UUID.nullable(false), this, "");

    /**
     * The column <code>audience_membership.joined_at</code>.
     */
    public final TableField<AudienceMembershipRecord, OffsetDateTime> JOINED_AT = createField(DSL.name("joined_at"), SQLDataType.TIMESTAMPWITHTIMEZONE(6), this, "");

    /**
     * The column <code>audience_membership.version</code>.
     */
    public final TableField<AudienceMembershipRecord, Long> VERSION = createField(DSL.name("version"), SQLDataType.BIGINT, this, "");

    private AudienceMembership(Name alias, Table<AudienceMembershipRecord> aliased) {
        this(alias, aliased, (Field<?>[]) null, null);
    }

    private AudienceMembership(Name alias, Table<AudienceMembershipRecord> aliased, Field<?>[] parameters, Condition where) {
        super(alias, null, aliased, parameters, DSL.comment(""), TableOptions.table(), where);
    }

    /**
     * Create an aliased <code>audience_membership</code> table reference
     */
    public AudienceMembership(String alias) {
        this(DSL.name(alias), AUDIENCE_MEMBERSHIP);
    }

    /**
     * Create an aliased <code>audience_membership</code> table reference
     */
    public AudienceMembership(Name alias) {
        this(alias, AUDIENCE_MEMBERSHIP);
    }

    /**
     * Create a <code>audience_membership</code> table reference
     */
    public AudienceMembership() {
        this(DSL.name("audience_membership"), null);
    }

    @Override
    public Schema getSchema() {
        return aliased() ? null : DefaultSchema.DEFAULT_SCHEMA;
    }

    @Override
    public UniqueKey<AudienceMembershipRecord> getPrimaryKey() {
        return Keys.AUDIENCE_MEMBERSHIP_PKEY;
    }

    @Override
    public AudienceMembership as(String alias) {
        return new AudienceMembership(DSL.name(alias), this);
    }

    @Override
    public AudienceMembership as(Name alias) {
        return new AudienceMembership(alias, this);
    }

    @Override
    public AudienceMembership as(Table<?> alias) {
        return new AudienceMembership(alias.getQualifiedName(), this);
    }

    /**
     * Rename this table
     */
    @Override
    public AudienceMembership rename(String name) {
        return new AudienceMembership(DSL.name(name), null);
    }

    /**
     * Rename this table
     */
    @Override
    public AudienceMembership rename(Name name) {
        return new AudienceMembership(name, null);
    }

    /**
     * Rename this table
     */
    @Override
    public AudienceMembership rename(Table<?> name) {
        return new AudienceMembership(name.getQualifiedName(), null);
    }

    /**
     * Create an inline derived table from this table
     */
    @Override
    public AudienceMembership where(Condition condition) {
        return new AudienceMembership(getQualifiedName(), aliased() ? this : null, null, Internal.condition(this, condition));
    }

    /**
     * Create an inline derived table from this table
     */
    @Override
    public AudienceMembership where(Collection<? extends Condition> conditions) {
        return where(DSL.and(conditions));
    }

    /**
     * Create an inline derived table from this table
     */
    @Override
    public AudienceMembership where(Condition... conditions) {
        return where(DSL.and(conditions));
    }

    /**
     * Create an inline derived table from this table
     */
    @Override
    public AudienceMembership where(Field<Boolean> condition) {
        return where(DSL.condition(condition));
    }

    /**
     * Create an inline derived table from this table
     */
    @Override
    @PlainSQL
    public AudienceMembership where(SQL condition) {
        return where(DSL.condition(condition));
    }

    /**
     * Create an inline derived table from this table
     */
    @Override
    @PlainSQL
    public AudienceMembership where(@Stringly.SQL String condition) {
        return where(DSL.condition(condition));
    }

    /**
     * Create an inline derived table from this table
     */
    @Override
    @PlainSQL
    public AudienceMembership where(@Stringly.SQL String condition, Object... binds) {
        return where(DSL.condition(condition, binds));
    }

    /**
     * Create an inline derived table from this table
     */
    @Override
    @PlainSQL
    public AudienceMembership where(@Stringly.SQL String condition, QueryPart... parts) {
        return where(DSL.condition(condition, parts));
    }

    /**
     * Create an inline derived table from this table
     */
    @Override
    public AudienceMembership whereExists(TableLike<?> select) {
        return where(DSL.exists(select));
    }

    /**
     * Create an inline derived table from this table
     */
    @Override
    public AudienceMembership whereNotExists(TableLike<?> select) {
        return where(DSL.notExists(select));
    }
}
