/*
 * This file is generated by jOOQ.
 */
package com.ogoma.marketing.infrastructure.jooq.tables;


import com.ogoma.marketing.infrastructure.jooq.DefaultSchema;
import com.ogoma.marketing.infrastructure.jooq.Keys;
import com.ogoma.marketing.infrastructure.jooq.tables.Campaigns.CampaignsPath;
import com.ogoma.marketing.infrastructure.jooq.tables.records.CampaignChannelsRecord;
import org.jooq.*;
import org.jooq.Record;
import org.jooq.impl.DSL;
import org.jooq.impl.Internal;
import org.jooq.impl.SQLDataType;
import org.jooq.impl.TableImpl;

import java.util.Arrays;
import java.util.Collection;
import java.util.List;
import java.util.UUID;


/**
 * This class is generated by jOOQ.
 */
@SuppressWarnings({ "all", "unchecked", "rawtypes", "this-escape" })
public class CampaignChannels extends TableImpl<CampaignChannelsRecord> {

    private static final long serialVersionUID = 1L;

    /**
     * The reference instance of <code>campaign_channels</code>
     */
    public static final CampaignChannels CAMPAIGN_CHANNELS = new CampaignChannels();

    /**
     * The class holding records for this type
     */
    @Override
    public Class<CampaignChannelsRecord> getRecordType() {
        return CampaignChannelsRecord.class;
    }

    /**
     * The column <code>campaign_channels.campaign_id</code>.
     */
    public final TableField<CampaignChannelsRecord, UUID> CAMPAIGN_ID = createField(DSL.name("campaign_id"), SQLDataType.UUID.nullable(false), this, "");

    /**
     * The column <code>campaign_channels.channel</code>.
     */
    public final TableField<CampaignChannelsRecord, String> CHANNEL = createField(DSL.name("channel"), SQLDataType.VARCHAR.nullable(false), this, "");

    private CampaignChannels(Name alias, Table<CampaignChannelsRecord> aliased) {
        this(alias, aliased, (Field<?>[]) null, null);
    }

    private CampaignChannels(Name alias, Table<CampaignChannelsRecord> aliased, Field<?>[] parameters, Condition where) {
        super(alias, null, aliased, parameters, DSL.comment(""), TableOptions.table(), where);
    }

    /**
     * Create an aliased <code>campaign_channels</code> table reference
     */
    public CampaignChannels(String alias) {
        this(DSL.name(alias), CAMPAIGN_CHANNELS);
    }

    /**
     * Create an aliased <code>campaign_channels</code> table reference
     */
    public CampaignChannels(Name alias) {
        this(alias, CAMPAIGN_CHANNELS);
    }

    /**
     * Create a <code>campaign_channels</code> table reference
     */
    public CampaignChannels() {
        this(DSL.name("campaign_channels"), null);
    }

    public <O extends Record> CampaignChannels(Table<O> path, ForeignKey<O, CampaignChannelsRecord> childPath, InverseForeignKey<O, CampaignChannelsRecord> parentPath) {
        super(path, childPath, parentPath, CAMPAIGN_CHANNELS);
    }

    /**
     * A subtype implementing {@link Path} for simplified path-based joins.
     */
    public static class CampaignChannelsPath extends CampaignChannels implements Path<CampaignChannelsRecord> {

        private static final long serialVersionUID = 1L;
        public <O extends Record> CampaignChannelsPath(Table<O> path, ForeignKey<O, CampaignChannelsRecord> childPath, InverseForeignKey<O, CampaignChannelsRecord> parentPath) {
            super(path, childPath, parentPath);
        }
        private CampaignChannelsPath(Name alias, Table<CampaignChannelsRecord> aliased) {
            super(alias, aliased);
        }

        @Override
        public CampaignChannelsPath as(String alias) {
            return new CampaignChannelsPath(DSL.name(alias), this);
        }

        @Override
        public CampaignChannelsPath as(Name alias) {
            return new CampaignChannelsPath(alias, this);
        }

        @Override
        public CampaignChannelsPath as(Table<?> alias) {
            return new CampaignChannelsPath(alias.getQualifiedName(), this);
        }
    }

    @Override
    public Schema getSchema() {
        return aliased() ? null : DefaultSchema.DEFAULT_SCHEMA;
    }

    @Override
    public UniqueKey<CampaignChannelsRecord> getPrimaryKey() {
        return Keys.CAMPAIGN_CHANNELS_PKEY;
    }

    @Override
    public List<ForeignKey<CampaignChannelsRecord, ?>> getReferences() {
        return Arrays.asList(Keys.CAMPAIGN_CHANNELS__CAMPAIGN_CHANNELS_CAMPAIGN_ID_FKEY);
    }

    private transient CampaignsPath _campaigns;

    /**
     * Get the implicit join path to the <code>campaigns</code> table.
     */
    public CampaignsPath campaigns() {
        if (_campaigns == null)
            _campaigns = new CampaignsPath(this, Keys.CAMPAIGN_CHANNELS__CAMPAIGN_CHANNELS_CAMPAIGN_ID_FKEY, null);

        return _campaigns;
    }

    @Override
    public CampaignChannels as(String alias) {
        return new CampaignChannels(DSL.name(alias), this);
    }

    @Override
    public CampaignChannels as(Name alias) {
        return new CampaignChannels(alias, this);
    }

    @Override
    public CampaignChannels as(Table<?> alias) {
        return new CampaignChannels(alias.getQualifiedName(), this);
    }

    /**
     * Rename this table
     */
    @Override
    public CampaignChannels rename(String name) {
        return new CampaignChannels(DSL.name(name), null);
    }

    /**
     * Rename this table
     */
    @Override
    public CampaignChannels rename(Name name) {
        return new CampaignChannels(name, null);
    }

    /**
     * Rename this table
     */
    @Override
    public CampaignChannels rename(Table<?> name) {
        return new CampaignChannels(name.getQualifiedName(), null);
    }

    /**
     * Create an inline derived table from this table
     */
    @Override
    public CampaignChannels where(Condition condition) {
        return new CampaignChannels(getQualifiedName(), aliased() ? this : null, null, Internal.condition(this, condition));
    }

    /**
     * Create an inline derived table from this table
     */
    @Override
    public CampaignChannels where(Collection<? extends Condition> conditions) {
        return where(DSL.and(conditions));
    }

    /**
     * Create an inline derived table from this table
     */
    @Override
    public CampaignChannels where(Condition... conditions) {
        return where(DSL.and(conditions));
    }

    /**
     * Create an inline derived table from this table
     */
    @Override
    public CampaignChannels where(Field<Boolean> condition) {
        return where(DSL.condition(condition));
    }

    /**
     * Create an inline derived table from this table
     */
    @Override
    @PlainSQL
    public CampaignChannels where(SQL condition) {
        return where(DSL.condition(condition));
    }

    /**
     * Create an inline derived table from this table
     */
    @Override
    @PlainSQL
    public CampaignChannels where(@Stringly.SQL String condition) {
        return where(DSL.condition(condition));
    }

    /**
     * Create an inline derived table from this table
     */
    @Override
    @PlainSQL
    public CampaignChannels where(@Stringly.SQL String condition, Object... binds) {
        return where(DSL.condition(condition, binds));
    }

    /**
     * Create an inline derived table from this table
     */
    @Override
    @PlainSQL
    public CampaignChannels where(@Stringly.SQL String condition, QueryPart... parts) {
        return where(DSL.condition(condition, parts));
    }

    /**
     * Create an inline derived table from this table
     */
    @Override
    public CampaignChannels whereExists(TableLike<?> select) {
        return where(DSL.exists(select));
    }

    /**
     * Create an inline derived table from this table
     */
    @Override
    public CampaignChannels whereNotExists(TableLike<?> select) {
        return where(DSL.notExists(select));
    }
}
