/*
 * This file is generated by jOOQ.
 */
package com.ogoma.marketing.infrastructure.jooq.tables;


import com.ogoma.marketing.infrastructure.jooq.DefaultSchema;
import com.ogoma.marketing.infrastructure.jooq.Keys;
import com.ogoma.marketing.infrastructure.jooq.tables.Campaigns.CampaignsPath;
import com.ogoma.marketing.infrastructure.jooq.tables.Segments.SegmentsPath;
import com.ogoma.marketing.infrastructure.jooq.tables.records.CampaignSegmentsRecord;

import java.util.Arrays;
import java.util.Collection;
import java.util.List;
import java.util.UUID;

import org.jooq.Condition;
import org.jooq.Field;
import org.jooq.ForeignKey;
import org.jooq.InverseForeignKey;
import org.jooq.Name;
import org.jooq.Path;
import org.jooq.PlainSQL;
import org.jooq.QueryPart;
import org.jooq.Record;
import org.jooq.SQL;
import org.jooq.Schema;
import org.jooq.Stringly;
import org.jooq.Table;
import org.jooq.TableField;
import org.jooq.TableLike;
import org.jooq.TableOptions;
import org.jooq.UniqueKey;
import org.jooq.impl.DSL;
import org.jooq.impl.Internal;
import org.jooq.impl.SQLDataType;
import org.jooq.impl.TableImpl;


/**
 * This class is generated by jOOQ.
 */
@SuppressWarnings({ "all", "unchecked", "rawtypes", "this-escape" })
public class CampaignSegments extends TableImpl<CampaignSegmentsRecord> {

    private static final long serialVersionUID = 1L;

    /**
     * The reference instance of <code>campaign_segments</code>
     */
    public static final CampaignSegments CAMPAIGN_SEGMENTS = new CampaignSegments();

    /**
     * The class holding records for this type
     */
    @Override
    public Class<CampaignSegmentsRecord> getRecordType() {
        return CampaignSegmentsRecord.class;
    }

    /**
     * The column <code>campaign_segments.campaign_id</code>.
     */
    public final TableField<CampaignSegmentsRecord, UUID> CAMPAIGN_ID = createField(DSL.name("campaign_id"), SQLDataType.UUID.nullable(false), this, "");

    /**
     * The column <code>campaign_segments.segment_id</code>.
     */
    public final TableField<CampaignSegmentsRecord, UUID> SEGMENT_ID = createField(DSL.name("segment_id"), SQLDataType.UUID.nullable(false), this, "");

    private CampaignSegments(Name alias, Table<CampaignSegmentsRecord> aliased) {
        this(alias, aliased, (Field<?>[]) null, null);
    }

    private CampaignSegments(Name alias, Table<CampaignSegmentsRecord> aliased, Field<?>[] parameters, Condition where) {
        super(alias, null, aliased, parameters, DSL.comment(""), TableOptions.table(), where);
    }

    /**
     * Create an aliased <code>campaign_segments</code> table reference
     */
    public CampaignSegments(String alias) {
        this(DSL.name(alias), CAMPAIGN_SEGMENTS);
    }

    /**
     * Create an aliased <code>campaign_segments</code> table reference
     */
    public CampaignSegments(Name alias) {
        this(alias, CAMPAIGN_SEGMENTS);
    }

    /**
     * Create a <code>campaign_segments</code> table reference
     */
    public CampaignSegments() {
        this(DSL.name("campaign_segments"), null);
    }

    public <O extends Record> CampaignSegments(Table<O> path, ForeignKey<O, CampaignSegmentsRecord> childPath, InverseForeignKey<O, CampaignSegmentsRecord> parentPath) {
        super(path, childPath, parentPath, CAMPAIGN_SEGMENTS);
    }

    /**
     * A subtype implementing {@link Path} for simplified path-based joins.
     */
    public static class CampaignSegmentsPath extends CampaignSegments implements Path<CampaignSegmentsRecord> {

        private static final long serialVersionUID = 1L;
        public <O extends Record> CampaignSegmentsPath(Table<O> path, ForeignKey<O, CampaignSegmentsRecord> childPath, InverseForeignKey<O, CampaignSegmentsRecord> parentPath) {
            super(path, childPath, parentPath);
        }
        private CampaignSegmentsPath(Name alias, Table<CampaignSegmentsRecord> aliased) {
            super(alias, aliased);
        }

        @Override
        public CampaignSegmentsPath as(String alias) {
            return new CampaignSegmentsPath(DSL.name(alias), this);
        }

        @Override
        public CampaignSegmentsPath as(Name alias) {
            return new CampaignSegmentsPath(alias, this);
        }

        @Override
        public CampaignSegmentsPath as(Table<?> alias) {
            return new CampaignSegmentsPath(alias.getQualifiedName(), this);
        }
    }

    @Override
    public Schema getSchema() {
        return aliased() ? null : DefaultSchema.DEFAULT_SCHEMA;
    }

    @Override
    public UniqueKey<CampaignSegmentsRecord> getPrimaryKey() {
        return Keys.CAMPAIGN_SEGMENTS_PKEY;
    }

    @Override
    public List<ForeignKey<CampaignSegmentsRecord, ?>> getReferences() {
        return Arrays.asList(Keys.CAMPAIGN_SEGMENTS__CAMPAIGN_SEGMENTS_CAMPAIGN_ID_FKEY, Keys.CAMPAIGN_SEGMENTS__CAMPAIGN_SEGMENTS_SEGMENT_ID_FKEY);
    }

    private transient CampaignsPath _campaigns;

    /**
     * Get the implicit join path to the <code>campaigns</code> table.
     */
    public CampaignsPath campaigns() {
        if (_campaigns == null)
            _campaigns = new CampaignsPath(this, Keys.CAMPAIGN_SEGMENTS__CAMPAIGN_SEGMENTS_CAMPAIGN_ID_FKEY, null);

        return _campaigns;
    }

    private transient SegmentsPath _segments;

    /**
     * Get the implicit join path to the <code>segments</code> table.
     */
    public SegmentsPath segments() {
        if (_segments == null)
            _segments = new SegmentsPath(this, Keys.CAMPAIGN_SEGMENTS__CAMPAIGN_SEGMENTS_SEGMENT_ID_FKEY, null);

        return _segments;
    }

    @Override
    public CampaignSegments as(String alias) {
        return new CampaignSegments(DSL.name(alias), this);
    }

    @Override
    public CampaignSegments as(Name alias) {
        return new CampaignSegments(alias, this);
    }

    @Override
    public CampaignSegments as(Table<?> alias) {
        return new CampaignSegments(alias.getQualifiedName(), this);
    }

    /**
     * Rename this table
     */
    @Override
    public CampaignSegments rename(String name) {
        return new CampaignSegments(DSL.name(name), null);
    }

    /**
     * Rename this table
     */
    @Override
    public CampaignSegments rename(Name name) {
        return new CampaignSegments(name, null);
    }

    /**
     * Rename this table
     */
    @Override
    public CampaignSegments rename(Table<?> name) {
        return new CampaignSegments(name.getQualifiedName(), null);
    }

    /**
     * Create an inline derived table from this table
     */
    @Override
    public CampaignSegments where(Condition condition) {
        return new CampaignSegments(getQualifiedName(), aliased() ? this : null, null, Internal.condition(this, condition));
    }

    /**
     * Create an inline derived table from this table
     */
    @Override
    public CampaignSegments where(Collection<? extends Condition> conditions) {
        return where(DSL.and(conditions));
    }

    /**
     * Create an inline derived table from this table
     */
    @Override
    public CampaignSegments where(Condition... conditions) {
        return where(DSL.and(conditions));
    }

    /**
     * Create an inline derived table from this table
     */
    @Override
    public CampaignSegments where(Field<Boolean> condition) {
        return where(DSL.condition(condition));
    }

    /**
     * Create an inline derived table from this table
     */
    @Override
    @PlainSQL
    public CampaignSegments where(SQL condition) {
        return where(DSL.condition(condition));
    }

    /**
     * Create an inline derived table from this table
     */
    @Override
    @PlainSQL
    public CampaignSegments where(@Stringly.SQL String condition) {
        return where(DSL.condition(condition));
    }

    /**
     * Create an inline derived table from this table
     */
    @Override
    @PlainSQL
    public CampaignSegments where(@Stringly.SQL String condition, Object... binds) {
        return where(DSL.condition(condition, binds));
    }

    /**
     * Create an inline derived table from this table
     */
    @Override
    @PlainSQL
    public CampaignSegments where(@Stringly.SQL String condition, QueryPart... parts) {
        return where(DSL.condition(condition, parts));
    }

    /**
     * Create an inline derived table from this table
     */
    @Override
    public CampaignSegments whereExists(TableLike<?> select) {
        return where(DSL.exists(select));
    }

    /**
     * Create an inline derived table from this table
     */
    @Override
    public CampaignSegments whereNotExists(TableLike<?> select) {
        return where(DSL.notExists(select));
    }
}
