/*
 * This file is generated by jOOQ.
 */
package com.ogoma.marketing.infrastructure.jooq.tables;


import com.ogoma.marketing.infrastructure.jooq.DefaultSchema;
import com.ogoma.marketing.infrastructure.jooq.Keys;
import com.ogoma.marketing.infrastructure.jooq.tables.Audiences.AudiencesPath;
import com.ogoma.marketing.infrastructure.jooq.tables.CampaignAudience.CampaignAudiencePath;
import com.ogoma.marketing.infrastructure.jooq.tables.CampaignChannels.CampaignChannelsPath;
import com.ogoma.marketing.infrastructure.jooq.tables.CampaignSegments.CampaignSegmentsPath;
import com.ogoma.marketing.infrastructure.jooq.tables.Segments.SegmentsPath;
import com.ogoma.marketing.infrastructure.jooq.tables.records.CampaignsRecord;
import org.jooq.*;
import org.jooq.Record;
import org.jooq.impl.DSL;
import org.jooq.impl.Internal;
import org.jooq.impl.SQLDataType;
import org.jooq.impl.TableImpl;

import java.time.LocalDateTime;
import java.time.OffsetDateTime;
import java.util.Collection;
import java.util.UUID;


/**
 * This class is generated by jOOQ.
 */
@SuppressWarnings({ "all", "unchecked", "rawtypes", "this-escape" })
public class Campaigns extends TableImpl<CampaignsRecord> {

    private static final long serialVersionUID = 1L;

    /**
     * The reference instance of <code>campaigns</code>
     */
    public static final Campaigns CAMPAIGNS = new Campaigns();

    /**
     * The class holding records for this type
     */
    @Override
    public Class<CampaignsRecord> getRecordType() {
        return CampaignsRecord.class;
    }

    /**
     * The column <code>campaigns.id</code>.
     */
    public final TableField<CampaignsRecord, UUID> ID = createField(DSL.name("id"), SQLDataType.UUID.nullable(false), this, "");

    /**
     * The column <code>campaigns.name</code>.
     */
    public final TableField<CampaignsRecord, String> NAME = createField(DSL.name("name"), SQLDataType.VARCHAR.nullable(false), this, "");

    /**
     * The column <code>campaigns.description</code>.
     */
    public final TableField<CampaignsRecord, String> DESCRIPTION = createField(DSL.name("description"), SQLDataType.VARCHAR, this, "");

    /**
     * The column <code>campaigns.version</code>.
     */
    public final TableField<CampaignsRecord, Long> VERSION = createField(DSL.name("version"), SQLDataType.BIGINT, this, "");

    /**
     * The column <code>campaigns.configuration</code>.
     */
    public final TableField<CampaignsRecord, JSONB> CONFIGURATION = createField(DSL.name("configuration"), SQLDataType.JSONB, this, "");

    /**
     * The column <code>campaigns.created_by</code>.
     */
    public final TableField<CampaignsRecord, String> CREATED_BY = createField(DSL.name("created_by"), SQLDataType.VARCHAR, this, "");

    /**
     * The column <code>campaigns.created_at</code>.
     */
    public final TableField<CampaignsRecord, OffsetDateTime> CREATED_AT = createField(DSL.name("created_at"), SQLDataType.TIMESTAMPWITHTIMEZONE(6), this, "");

    /**
     * The column <code>campaigns.last_updated_at</code>.
     */
    public final TableField<CampaignsRecord, LocalDateTime> LAST_UPDATED_AT = createField(DSL.name("last_updated_at"), SQLDataType.LOCALDATETIME(6), this, "");

    /**
     * The column <code>campaigns.last_updated_by</code>.
     */
    public final TableField<CampaignsRecord, String> LAST_UPDATED_BY = createField(DSL.name("last_updated_by"), SQLDataType.VARCHAR, this, "");

    /**
     * The column <code>campaigns.status</code>.
     */
    public final TableField<CampaignsRecord, String> STATUS = createField(DSL.name("status"), SQLDataType.VARCHAR, this, "");

    /**
     * The column <code>campaigns.sms_template_id</code>.
     */
    public final TableField<CampaignsRecord, UUID> SMS_TEMPLATE_ID = createField(DSL.name("sms_template_id"), SQLDataType.UUID, this, "");

    /**
     * The column <code>campaigns.email_template_id</code>.
     */
    public final TableField<CampaignsRecord, UUID> EMAIL_TEMPLATE_ID = createField(DSL.name("email_template_id"), SQLDataType.UUID, this, "");

    /**
     * The column <code>campaigns.channels</code>.
     */
    public final TableField<CampaignsRecord, String[]> CHANNELS = createField(DSL.name("channels"), SQLDataType.VARCHAR.array(), this, "");

    private Campaigns(Name alias, Table<CampaignsRecord> aliased) {
        this(alias, aliased, (Field<?>[]) null, null);
    }

    private Campaigns(Name alias, Table<CampaignsRecord> aliased, Field<?>[] parameters, Condition where) {
        super(alias, null, aliased, parameters, DSL.comment(""), TableOptions.table(), where);
    }

    /**
     * Create an aliased <code>campaigns</code> table reference
     */
    public Campaigns(String alias) {
        this(DSL.name(alias), CAMPAIGNS);
    }

    /**
     * Create an aliased <code>campaigns</code> table reference
     */
    public Campaigns(Name alias) {
        this(alias, CAMPAIGNS);
    }

    /**
     * Create a <code>campaigns</code> table reference
     */
    public Campaigns() {
        this(DSL.name("campaigns"), null);
    }

    public <O extends Record> Campaigns(Table<O> path, ForeignKey<O, CampaignsRecord> childPath, InverseForeignKey<O, CampaignsRecord> parentPath) {
        super(path, childPath, parentPath, CAMPAIGNS);
    }

    /**
     * A subtype implementing {@link Path} for simplified path-based joins.
     */
    public static class CampaignsPath extends Campaigns implements Path<CampaignsRecord> {

        private static final long serialVersionUID = 1L;
        public <O extends Record> CampaignsPath(Table<O> path, ForeignKey<O, CampaignsRecord> childPath, InverseForeignKey<O, CampaignsRecord> parentPath) {
            super(path, childPath, parentPath);
        }
        private CampaignsPath(Name alias, Table<CampaignsRecord> aliased) {
            super(alias, aliased);
        }

        @Override
        public CampaignsPath as(String alias) {
            return new CampaignsPath(DSL.name(alias), this);
        }

        @Override
        public CampaignsPath as(Name alias) {
            return new CampaignsPath(alias, this);
        }

        @Override
        public CampaignsPath as(Table<?> alias) {
            return new CampaignsPath(alias.getQualifiedName(), this);
        }
    }

    @Override
    public Schema getSchema() {
        return aliased() ? null : DefaultSchema.DEFAULT_SCHEMA;
    }

    @Override
    public UniqueKey<CampaignsRecord> getPrimaryKey() {
        return Keys.CAMPAIGNS_PKEY;
    }

    private transient CampaignAudiencePath _campaignAudience;

    /**
     * Get the implicit to-many join path to the <code>campaign_audience</code>
     * table
     */
    public CampaignAudiencePath campaignAudience() {
        if (_campaignAudience == null)
            _campaignAudience = new CampaignAudiencePath(this, null, Keys.CAMPAIGN_AUDIENCE__CAMPAIGN_AUDIENCE_CAMPAIGN_ID_FKEY.getInverseKey());

        return _campaignAudience;
    }

    private transient CampaignChannelsPath _campaignChannels;

    /**
     * Get the implicit to-many join path to the <code>campaign_channels</code>
     * table
     */
    public CampaignChannelsPath campaignChannels() {
        if (_campaignChannels == null)
            _campaignChannels = new CampaignChannelsPath(this, null, Keys.CAMPAIGN_CHANNELS__CAMPAIGN_CHANNELS_CAMPAIGN_ID_FKEY.getInverseKey());

        return _campaignChannels;
    }

    private transient CampaignSegmentsPath _campaignSegments;

    /**
     * Get the implicit to-many join path to the <code>campaign_segments</code>
     * table
     */
    public CampaignSegmentsPath campaignSegments() {
        if (_campaignSegments == null)
            _campaignSegments = new CampaignSegmentsPath(this, null, Keys.CAMPAIGN_SEGMENTS__CAMPAIGN_SEGMENTS_CAMPAIGN_ID_FKEY.getInverseKey());

        return _campaignSegments;
    }

    /**
     * Get the implicit many-to-many join path to the <code>audiences</code>
     * table
     */
    public AudiencesPath audiences() {
        return campaignAudience().audiences();
    }

    /**
     * Get the implicit many-to-many join path to the <code>segments</code>
     * table
     */
    public SegmentsPath segments() {
        return campaignSegments().segments();
    }

    @Override
    public Campaigns as(String alias) {
        return new Campaigns(DSL.name(alias), this);
    }

    @Override
    public Campaigns as(Name alias) {
        return new Campaigns(alias, this);
    }

    @Override
    public Campaigns as(Table<?> alias) {
        return new Campaigns(alias.getQualifiedName(), this);
    }

    /**
     * Rename this table
     */
    @Override
    public Campaigns rename(String name) {
        return new Campaigns(DSL.name(name), null);
    }

    /**
     * Rename this table
     */
    @Override
    public Campaigns rename(Name name) {
        return new Campaigns(name, null);
    }

    /**
     * Rename this table
     */
    @Override
    public Campaigns rename(Table<?> name) {
        return new Campaigns(name.getQualifiedName(), null);
    }

    /**
     * Create an inline derived table from this table
     */
    @Override
    public Campaigns where(Condition condition) {
        return new Campaigns(getQualifiedName(), aliased() ? this : null, null, Internal.condition(this, condition));
    }

    /**
     * Create an inline derived table from this table
     */
    @Override
    public Campaigns where(Collection<? extends Condition> conditions) {
        return where(DSL.and(conditions));
    }

    /**
     * Create an inline derived table from this table
     */
    @Override
    public Campaigns where(Condition... conditions) {
        return where(DSL.and(conditions));
    }

    /**
     * Create an inline derived table from this table
     */
    @Override
    public Campaigns where(Field<Boolean> condition) {
        return where(DSL.condition(condition));
    }

    /**
     * Create an inline derived table from this table
     */
    @Override
    @PlainSQL
    public Campaigns where(SQL condition) {
        return where(DSL.condition(condition));
    }

    /**
     * Create an inline derived table from this table
     */
    @Override
    @PlainSQL
    public Campaigns where(@Stringly.SQL String condition) {
        return where(DSL.condition(condition));
    }

    /**
     * Create an inline derived table from this table
     */
    @Override
    @PlainSQL
    public Campaigns where(@Stringly.SQL String condition, Object... binds) {
        return where(DSL.condition(condition, binds));
    }

    /**
     * Create an inline derived table from this table
     */
    @Override
    @PlainSQL
    public Campaigns where(@Stringly.SQL String condition, QueryPart... parts) {
        return where(DSL.condition(condition, parts));
    }

    /**
     * Create an inline derived table from this table
     */
    @Override
    public Campaigns whereExists(TableLike<?> select) {
        return where(DSL.exists(select));
    }

    /**
     * Create an inline derived table from this table
     */
    @Override
    public Campaigns whereNotExists(TableLike<?> select) {
        return where(DSL.notExists(select));
    }
}
