/*
 * This file is generated by jOOQ.
 */
package com.ogoma.marketing.infrastructure.jooq.tables;


import com.ogoma.marketing.infrastructure.jooq.DefaultSchema;
import com.ogoma.marketing.infrastructure.jooq.Keys;
import com.ogoma.marketing.infrastructure.jooq.tables.Audiences.AudiencesPath;
import com.ogoma.marketing.infrastructure.jooq.tables.Campaigns.CampaignsPath;
import com.ogoma.marketing.infrastructure.jooq.tables.records.CampaignAudienceRecord;
import org.jooq.*;
import org.jooq.Record;
import org.jooq.impl.DSL;
import org.jooq.impl.Internal;
import org.jooq.impl.SQLDataType;
import org.jooq.impl.TableImpl;

import java.util.Arrays;
import java.util.Collection;
import java.util.List;
import java.util.UUID;


/**
 * This class is generated by jOOQ.
 */
@SuppressWarnings({ "all", "unchecked", "rawtypes", "this-escape" })
public class CampaignAudience extends TableImpl<CampaignAudienceRecord> {

    private static final long serialVersionUID = 1L;

    /**
     * The reference instance of <code>campaign_audience</code>
     */
    public static final CampaignAudience CAMPAIGN_AUDIENCE = new CampaignAudience();

    /**
     * The class holding records for this type
     */
    @Override
    public Class<CampaignAudienceRecord> getRecordType() {
        return CampaignAudienceRecord.class;
    }

    /**
     * The column <code>campaign_audience.campaign_id</code>.
     */
    public final TableField<CampaignAudienceRecord, UUID> CAMPAIGN_ID = createField(DSL.name("campaign_id"), SQLDataType.UUID.nullable(false), this, "");

    /**
     * The column <code>campaign_audience.audience_id</code>.
     */
    public final TableField<CampaignAudienceRecord, UUID> AUDIENCE_ID = createField(DSL.name("audience_id"), SQLDataType.UUID.nullable(false), this, "");

    private CampaignAudience(Name alias, Table<CampaignAudienceRecord> aliased) {
        this(alias, aliased, (Field<?>[]) null, null);
    }

    private CampaignAudience(Name alias, Table<CampaignAudienceRecord> aliased, Field<?>[] parameters, Condition where) {
        super(alias, null, aliased, parameters, DSL.comment(""), TableOptions.table(), where);
    }

    /**
     * Create an aliased <code>campaign_audience</code> table reference
     */
    public CampaignAudience(String alias) {
        this(DSL.name(alias), CAMPAIGN_AUDIENCE);
    }

    /**
     * Create an aliased <code>campaign_audience</code> table reference
     */
    public CampaignAudience(Name alias) {
        this(alias, CAMPAIGN_AUDIENCE);
    }

    /**
     * Create a <code>campaign_audience</code> table reference
     */
    public CampaignAudience() {
        this(DSL.name("campaign_audience"), null);
    }

    public <O extends Record> CampaignAudience(Table<O> path, ForeignKey<O, CampaignAudienceRecord> childPath, InverseForeignKey<O, CampaignAudienceRecord> parentPath) {
        super(path, childPath, parentPath, CAMPAIGN_AUDIENCE);
    }

    /**
     * A subtype implementing {@link Path} for simplified path-based joins.
     */
    public static class CampaignAudiencePath extends CampaignAudience implements Path<CampaignAudienceRecord> {

        private static final long serialVersionUID = 1L;
        public <O extends Record> CampaignAudiencePath(Table<O> path, ForeignKey<O, CampaignAudienceRecord> childPath, InverseForeignKey<O, CampaignAudienceRecord> parentPath) {
            super(path, childPath, parentPath);
        }
        private CampaignAudiencePath(Name alias, Table<CampaignAudienceRecord> aliased) {
            super(alias, aliased);
        }

        @Override
        public CampaignAudiencePath as(String alias) {
            return new CampaignAudiencePath(DSL.name(alias), this);
        }

        @Override
        public CampaignAudiencePath as(Name alias) {
            return new CampaignAudiencePath(alias, this);
        }

        @Override
        public CampaignAudiencePath as(Table<?> alias) {
            return new CampaignAudiencePath(alias.getQualifiedName(), this);
        }
    }

    @Override
    public Schema getSchema() {
        return aliased() ? null : DefaultSchema.DEFAULT_SCHEMA;
    }

    @Override
    public UniqueKey<CampaignAudienceRecord> getPrimaryKey() {
        return Keys.CAMPAIGN_AUDIENCE_PKEY;
    }

    @Override
    public List<ForeignKey<CampaignAudienceRecord, ?>> getReferences() {
        return Arrays.asList(Keys.CAMPAIGN_AUDIENCE__CAMPAIGN_AUDIENCE_AUDIENCE_ID_FKEY, Keys.CAMPAIGN_AUDIENCE__CAMPAIGN_AUDIENCE_CAMPAIGN_ID_FKEY);
    }

    private transient AudiencesPath _audiences;

    /**
     * Get the implicit join path to the <code>audiences</code> table.
     */
    public AudiencesPath audiences() {
        if (_audiences == null)
            _audiences = new AudiencesPath(this, Keys.CAMPAIGN_AUDIENCE__CAMPAIGN_AUDIENCE_AUDIENCE_ID_FKEY, null);

        return _audiences;
    }

    private transient CampaignsPath _campaigns;

    /**
     * Get the implicit join path to the <code>campaigns</code> table.
     */
    public CampaignsPath campaigns() {
        if (_campaigns == null)
            _campaigns = new CampaignsPath(this, Keys.CAMPAIGN_AUDIENCE__CAMPAIGN_AUDIENCE_CAMPAIGN_ID_FKEY, null);

        return _campaigns;
    }

    @Override
    public CampaignAudience as(String alias) {
        return new CampaignAudience(DSL.name(alias), this);
    }

    @Override
    public CampaignAudience as(Name alias) {
        return new CampaignAudience(alias, this);
    }

    @Override
    public CampaignAudience as(Table<?> alias) {
        return new CampaignAudience(alias.getQualifiedName(), this);
    }

    /**
     * Rename this table
     */
    @Override
    public CampaignAudience rename(String name) {
        return new CampaignAudience(DSL.name(name), null);
    }

    /**
     * Rename this table
     */
    @Override
    public CampaignAudience rename(Name name) {
        return new CampaignAudience(name, null);
    }

    /**
     * Rename this table
     */
    @Override
    public CampaignAudience rename(Table<?> name) {
        return new CampaignAudience(name.getQualifiedName(), null);
    }

    /**
     * Create an inline derived table from this table
     */
    @Override
    public CampaignAudience where(Condition condition) {
        return new CampaignAudience(getQualifiedName(), aliased() ? this : null, null, Internal.condition(this, condition));
    }

    /**
     * Create an inline derived table from this table
     */
    @Override
    public CampaignAudience where(Collection<? extends Condition> conditions) {
        return where(DSL.and(conditions));
    }

    /**
     * Create an inline derived table from this table
     */
    @Override
    public CampaignAudience where(Condition... conditions) {
        return where(DSL.and(conditions));
    }

    /**
     * Create an inline derived table from this table
     */
    @Override
    public CampaignAudience where(Field<Boolean> condition) {
        return where(DSL.condition(condition));
    }

    /**
     * Create an inline derived table from this table
     */
    @Override
    @PlainSQL
    public CampaignAudience where(SQL condition) {
        return where(DSL.condition(condition));
    }

    /**
     * Create an inline derived table from this table
     */
    @Override
    @PlainSQL
    public CampaignAudience where(@Stringly.SQL String condition) {
        return where(DSL.condition(condition));
    }

    /**
     * Create an inline derived table from this table
     */
    @Override
    @PlainSQL
    public CampaignAudience where(@Stringly.SQL String condition, Object... binds) {
        return where(DSL.condition(condition, binds));
    }

    /**
     * Create an inline derived table from this table
     */
    @Override
    @PlainSQL
    public CampaignAudience where(@Stringly.SQL String condition, QueryPart... parts) {
        return where(DSL.condition(condition, parts));
    }

    /**
     * Create an inline derived table from this table
     */
    @Override
    public CampaignAudience whereExists(TableLike<?> select) {
        return where(DSL.exists(select));
    }

    /**
     * Create an inline derived table from this table
     */
    @Override
    public CampaignAudience whereNotExists(TableLike<?> select) {
        return where(DSL.notExists(select));
    }
}
