/*
 * This file is generated by jOOQ.
 */
package com.ogoma.marketing.infrastructure.jooq.tables;


import com.ogoma.marketing.infrastructure.jooq.DefaultSchema;
import com.ogoma.marketing.infrastructure.jooq.Keys;
import com.ogoma.marketing.infrastructure.jooq.tables.Contacts.ContactsPath;
import com.ogoma.marketing.infrastructure.jooq.tables.records.ContactAttributeValuesRecord;

import java.util.Arrays;
import java.util.Collection;
import java.util.List;
import java.util.UUID;

import org.jooq.Condition;
import org.jooq.Field;
import org.jooq.ForeignKey;
import org.jooq.InverseForeignKey;
import org.jooq.Name;
import org.jooq.Path;
import org.jooq.PlainSQL;
import org.jooq.QueryPart;
import org.jooq.Record;
import org.jooq.SQL;
import org.jooq.Schema;
import org.jooq.Stringly;
import org.jooq.Table;
import org.jooq.TableField;
import org.jooq.TableLike;
import org.jooq.TableOptions;
import org.jooq.UniqueKey;
import org.jooq.impl.DSL;
import org.jooq.impl.Internal;
import org.jooq.impl.SQLDataType;
import org.jooq.impl.TableImpl;


/**
 * This class is generated by jOOQ.
 */
@SuppressWarnings({ "all", "unchecked", "rawtypes", "this-escape" })
public class ContactAttributeValues extends TableImpl<ContactAttributeValuesRecord> {

    private static final long serialVersionUID = 1L;

    /**
     * The reference instance of <code>contact_attribute_values</code>
     */
    public static final ContactAttributeValues CONTACT_ATTRIBUTE_VALUES = new ContactAttributeValues();

    /**
     * The class holding records for this type
     */
    @Override
    public Class<ContactAttributeValuesRecord> getRecordType() {
        return ContactAttributeValuesRecord.class;
    }

    /**
     * The column <code>contact_attribute_values.contact_id</code>.
     */
    public final TableField<ContactAttributeValuesRecord, UUID> CONTACT_ID = createField(DSL.name("contact_id"), SQLDataType.UUID.nullable(false), this, "");

    /**
     * The column <code>contact_attribute_values.attribute</code>.
     */
    public final TableField<ContactAttributeValuesRecord, String> ATTRIBUTE = createField(DSL.name("attribute"), SQLDataType.VARCHAR.nullable(false), this, "");

    /**
     * The column <code>contact_attribute_values.value</code>.
     */
    public final TableField<ContactAttributeValuesRecord, String> VALUE = createField(DSL.name("value"), SQLDataType.VARCHAR.nullable(false), this, "");

    private ContactAttributeValues(Name alias, Table<ContactAttributeValuesRecord> aliased) {
        this(alias, aliased, (Field<?>[]) null, null);
    }

    private ContactAttributeValues(Name alias, Table<ContactAttributeValuesRecord> aliased, Field<?>[] parameters, Condition where) {
        super(alias, null, aliased, parameters, DSL.comment(""), TableOptions.table(), where);
    }

    /**
     * Create an aliased <code>contact_attribute_values</code> table reference
     */
    public ContactAttributeValues(String alias) {
        this(DSL.name(alias), CONTACT_ATTRIBUTE_VALUES);
    }

    /**
     * Create an aliased <code>contact_attribute_values</code> table reference
     */
    public ContactAttributeValues(Name alias) {
        this(alias, CONTACT_ATTRIBUTE_VALUES);
    }

    /**
     * Create a <code>contact_attribute_values</code> table reference
     */
    public ContactAttributeValues() {
        this(DSL.name("contact_attribute_values"), null);
    }

    public <O extends Record> ContactAttributeValues(Table<O> path, ForeignKey<O, ContactAttributeValuesRecord> childPath, InverseForeignKey<O, ContactAttributeValuesRecord> parentPath) {
        super(path, childPath, parentPath, CONTACT_ATTRIBUTE_VALUES);
    }

    /**
     * A subtype implementing {@link Path} for simplified path-based joins.
     */
    public static class ContactAttributeValuesPath extends ContactAttributeValues implements Path<ContactAttributeValuesRecord> {

        private static final long serialVersionUID = 1L;
        public <O extends Record> ContactAttributeValuesPath(Table<O> path, ForeignKey<O, ContactAttributeValuesRecord> childPath, InverseForeignKey<O, ContactAttributeValuesRecord> parentPath) {
            super(path, childPath, parentPath);
        }
        private ContactAttributeValuesPath(Name alias, Table<ContactAttributeValuesRecord> aliased) {
            super(alias, aliased);
        }

        @Override
        public ContactAttributeValuesPath as(String alias) {
            return new ContactAttributeValuesPath(DSL.name(alias), this);
        }

        @Override
        public ContactAttributeValuesPath as(Name alias) {
            return new ContactAttributeValuesPath(alias, this);
        }

        @Override
        public ContactAttributeValuesPath as(Table<?> alias) {
            return new ContactAttributeValuesPath(alias.getQualifiedName(), this);
        }
    }

    @Override
    public Schema getSchema() {
        return aliased() ? null : DefaultSchema.DEFAULT_SCHEMA;
    }

    @Override
    public UniqueKey<ContactAttributeValuesRecord> getPrimaryKey() {
        return Keys.CONTACT_ATTRIBUTE_VALUES_PKEY;
    }

    @Override
    public List<ForeignKey<ContactAttributeValuesRecord, ?>> getReferences() {
        return Arrays.asList(Keys.CONTACT_ATTRIBUTE_VALUES__CONTACT_ATTRIBUTE_VALUES_CONTACT_ID_FKEY);
    }

    private transient ContactsPath _contacts;

    /**
     * Get the implicit join path to the <code>contacts</code> table.
     */
    public ContactsPath contacts() {
        if (_contacts == null)
            _contacts = new ContactsPath(this, Keys.CONTACT_ATTRIBUTE_VALUES__CONTACT_ATTRIBUTE_VALUES_CONTACT_ID_FKEY, null);

        return _contacts;
    }

    @Override
    public ContactAttributeValues as(String alias) {
        return new ContactAttributeValues(DSL.name(alias), this);
    }

    @Override
    public ContactAttributeValues as(Name alias) {
        return new ContactAttributeValues(alias, this);
    }

    @Override
    public ContactAttributeValues as(Table<?> alias) {
        return new ContactAttributeValues(alias.getQualifiedName(), this);
    }

    /**
     * Rename this table
     */
    @Override
    public ContactAttributeValues rename(String name) {
        return new ContactAttributeValues(DSL.name(name), null);
    }

    /**
     * Rename this table
     */
    @Override
    public ContactAttributeValues rename(Name name) {
        return new ContactAttributeValues(name, null);
    }

    /**
     * Rename this table
     */
    @Override
    public ContactAttributeValues rename(Table<?> name) {
        return new ContactAttributeValues(name.getQualifiedName(), null);
    }

    /**
     * Create an inline derived table from this table
     */
    @Override
    public ContactAttributeValues where(Condition condition) {
        return new ContactAttributeValues(getQualifiedName(), aliased() ? this : null, null, Internal.condition(this, condition));
    }

    /**
     * Create an inline derived table from this table
     */
    @Override
    public ContactAttributeValues where(Collection<? extends Condition> conditions) {
        return where(DSL.and(conditions));
    }

    /**
     * Create an inline derived table from this table
     */
    @Override
    public ContactAttributeValues where(Condition... conditions) {
        return where(DSL.and(conditions));
    }

    /**
     * Create an inline derived table from this table
     */
    @Override
    public ContactAttributeValues where(Field<Boolean> condition) {
        return where(DSL.condition(condition));
    }

    /**
     * Create an inline derived table from this table
     */
    @Override
    @PlainSQL
    public ContactAttributeValues where(SQL condition) {
        return where(DSL.condition(condition));
    }

    /**
     * Create an inline derived table from this table
     */
    @Override
    @PlainSQL
    public ContactAttributeValues where(@Stringly.SQL String condition) {
        return where(DSL.condition(condition));
    }

    /**
     * Create an inline derived table from this table
     */
    @Override
    @PlainSQL
    public ContactAttributeValues where(@Stringly.SQL String condition, Object... binds) {
        return where(DSL.condition(condition, binds));
    }

    /**
     * Create an inline derived table from this table
     */
    @Override
    @PlainSQL
    public ContactAttributeValues where(@Stringly.SQL String condition, QueryPart... parts) {
        return where(DSL.condition(condition, parts));
    }

    /**
     * Create an inline derived table from this table
     */
    @Override
    public ContactAttributeValues whereExists(TableLike<?> select) {
        return where(DSL.exists(select));
    }

    /**
     * Create an inline derived table from this table
     */
    @Override
    public ContactAttributeValues whereNotExists(TableLike<?> select) {
        return where(DSL.notExists(select));
    }
}
