/*
 * This file is generated by jOOQ.
 */
package com.ogoma.marketing.infrastructure.jooq.tables;


import com.ogoma.marketing.infrastructure.jooq.DefaultSchema;
import com.ogoma.marketing.infrastructure.jooq.Keys;
import com.ogoma.marketing.infrastructure.jooq.tables.ContactAttributeValues.ContactAttributeValuesPath;
import com.ogoma.marketing.infrastructure.jooq.tables.records.ContactsRecord;
import org.jooq.*;
import org.jooq.Record;
import org.jooq.impl.DSL;
import org.jooq.impl.Internal;
import org.jooq.impl.SQLDataType;
import org.jooq.impl.TableImpl;

import java.time.OffsetDateTime;
import java.util.Collection;
import java.util.UUID;


/**
 * This class is generated by jOOQ.
 */
@SuppressWarnings({ "all", "unchecked", "rawtypes", "this-escape" })
public class Contacts extends TableImpl<ContactsRecord> {

    private static final long serialVersionUID = 1L;

    /**
     * The reference instance of <code>contacts</code>
     */
    public static final Contacts CONTACTS = new Contacts();

    /**
     * The class holding records for this type
     */
    @Override
    public Class<ContactsRecord> getRecordType() {
        return ContactsRecord.class;
    }

    /**
     * The column <code>contacts.id</code>.
     */
    public final TableField<ContactsRecord, UUID> ID = createField(DSL.name("id"), SQLDataType.UUID.nullable(false), this, "");

    /**
     * The column <code>contacts.first_name</code>.
     */
    public final TableField<ContactsRecord, String> FIRST_NAME = createField(DSL.name("first_name"), SQLDataType.VARCHAR.nullable(false), this, "");

    /**
     * The column <code>contacts.last_name</code>.
     */
    public final TableField<ContactsRecord, String> LAST_NAME = createField(DSL.name("last_name"), SQLDataType.VARCHAR.nullable(false), this, "");

    /**
     * The column <code>contacts.email</code>.
     */
    public final TableField<ContactsRecord, String> EMAIL = createField(DSL.name("email"), SQLDataType.VARCHAR.nullable(false), this, "");

    /**
     * The column <code>contacts.created_at</code>.
     */
    public final TableField<ContactsRecord, OffsetDateTime> CREATED_AT = createField(DSL.name("created_at"), SQLDataType.TIMESTAMPWITHTIMEZONE(6).nullable(false), this, "");

    /**
     * The column <code>contacts.version</code>.
     */
    public final TableField<ContactsRecord, Long> VERSION = createField(DSL.name("version"), SQLDataType.BIGINT.nullable(false), this, "");

    /**
     * The column <code>contacts.attributtes</code>.
     */
    public final TableField<ContactsRecord, JSONB> ATTRIBUTTES = createField(DSL.name("attributtes"), SQLDataType.JSONB, this, "");

    /**
     * The column <code>contacts.created_by</code>.
     */
    public final TableField<ContactsRecord, String> CREATED_BY = createField(DSL.name("created_by"), SQLDataType.VARCHAR.nullable(false), this, "");

    /**
     * The column <code>contacts.last_updated_at</code>.
     */
    public final TableField<ContactsRecord, OffsetDateTime> LAST_UPDATED_AT = createField(DSL.name("last_updated_at"), SQLDataType.TIMESTAMPWITHTIMEZONE(6).nullable(false), this, "");

    /**
     * The column <code>contacts.last_updated_by</code>.
     */
    public final TableField<ContactsRecord, String> LAST_UPDATED_BY = createField(DSL.name("last_updated_by"), SQLDataType.VARCHAR.nullable(false), this, "");

    /**
     * The column <code>contacts.phone_number</code>.
     */
    public final TableField<ContactsRecord, String> PHONE_NUMBER = createField(DSL.name("phone_number"), SQLDataType.VARCHAR(255), this, "");

    private Contacts(Name alias, Table<ContactsRecord> aliased) {
        this(alias, aliased, (Field<?>[]) null, null);
    }

    private Contacts(Name alias, Table<ContactsRecord> aliased, Field<?>[] parameters, Condition where) {
        super(alias, null, aliased, parameters, DSL.comment(""), TableOptions.table(), where);
    }

    /**
     * Create an aliased <code>contacts</code> table reference
     */
    public Contacts(String alias) {
        this(DSL.name(alias), CONTACTS);
    }

    /**
     * Create an aliased <code>contacts</code> table reference
     */
    public Contacts(Name alias) {
        this(alias, CONTACTS);
    }

    /**
     * Create a <code>contacts</code> table reference
     */
    public Contacts() {
        this(DSL.name("contacts"), null);
    }

    public <O extends Record> Contacts(Table<O> path, ForeignKey<O, ContactsRecord> childPath, InverseForeignKey<O, ContactsRecord> parentPath) {
        super(path, childPath, parentPath, CONTACTS);
    }

    /**
     * A subtype implementing {@link Path} for simplified path-based joins.
     */
    public static class ContactsPath extends Contacts implements Path<ContactsRecord> {

        private static final long serialVersionUID = 1L;
        public <O extends Record> ContactsPath(Table<O> path, ForeignKey<O, ContactsRecord> childPath, InverseForeignKey<O, ContactsRecord> parentPath) {
            super(path, childPath, parentPath);
        }
        private ContactsPath(Name alias, Table<ContactsRecord> aliased) {
            super(alias, aliased);
        }

        @Override
        public ContactsPath as(String alias) {
            return new ContactsPath(DSL.name(alias), this);
        }

        @Override
        public ContactsPath as(Name alias) {
            return new ContactsPath(alias, this);
        }

        @Override
        public ContactsPath as(Table<?> alias) {
            return new ContactsPath(alias.getQualifiedName(), this);
        }
    }

    @Override
    public Schema getSchema() {
        return aliased() ? null : DefaultSchema.DEFAULT_SCHEMA;
    }

    @Override
    public UniqueKey<ContactsRecord> getPrimaryKey() {
        return Keys.CONTACTS_PKEY;
    }

    private transient ContactAttributeValuesPath _contactAttributeValues;

    /**
     * Get the implicit to-many join path to the
     * <code>contact_attribute_values</code> table
     */
    public ContactAttributeValuesPath contactAttributeValues() {
        if (_contactAttributeValues == null)
            _contactAttributeValues = new ContactAttributeValuesPath(this, null, Keys.CONTACT_ATTRIBUTE_VALUES__CONTACT_ATTRIBUTE_VALUES_CONTACT_ID_FKEY.getInverseKey());

        return _contactAttributeValues;
    }

    @Override
    public Contacts as(String alias) {
        return new Contacts(DSL.name(alias), this);
    }

    @Override
    public Contacts as(Name alias) {
        return new Contacts(alias, this);
    }

    @Override
    public Contacts as(Table<?> alias) {
        return new Contacts(alias.getQualifiedName(), this);
    }

    /**
     * Rename this table
     */
    @Override
    public Contacts rename(String name) {
        return new Contacts(DSL.name(name), null);
    }

    /**
     * Rename this table
     */
    @Override
    public Contacts rename(Name name) {
        return new Contacts(name, null);
    }

    /**
     * Rename this table
     */
    @Override
    public Contacts rename(Table<?> name) {
        return new Contacts(name.getQualifiedName(), null);
    }

    /**
     * Create an inline derived table from this table
     */
    @Override
    public Contacts where(Condition condition) {
        return new Contacts(getQualifiedName(), aliased() ? this : null, null, Internal.condition(this, condition));
    }

    /**
     * Create an inline derived table from this table
     */
    @Override
    public Contacts where(Collection<? extends Condition> conditions) {
        return where(DSL.and(conditions));
    }

    /**
     * Create an inline derived table from this table
     */
    @Override
    public Contacts where(Condition... conditions) {
        return where(DSL.and(conditions));
    }

    /**
     * Create an inline derived table from this table
     */
    @Override
    public Contacts where(Field<Boolean> condition) {
        return where(DSL.condition(condition));
    }

    /**
     * Create an inline derived table from this table
     */
    @Override
    @PlainSQL
    public Contacts where(SQL condition) {
        return where(DSL.condition(condition));
    }

    /**
     * Create an inline derived table from this table
     */
    @Override
    @PlainSQL
    public Contacts where(@Stringly.SQL String condition) {
        return where(DSL.condition(condition));
    }

    /**
     * Create an inline derived table from this table
     */
    @Override
    @PlainSQL
    public Contacts where(@Stringly.SQL String condition, Object... binds) {
        return where(DSL.condition(condition, binds));
    }

    /**
     * Create an inline derived table from this table
     */
    @Override
    @PlainSQL
    public Contacts where(@Stringly.SQL String condition, QueryPart... parts) {
        return where(DSL.condition(condition, parts));
    }

    /**
     * Create an inline derived table from this table
     */
    @Override
    public Contacts whereExists(TableLike<?> select) {
        return where(DSL.exists(select));
    }

    /**
     * Create an inline derived table from this table
     */
    @Override
    public Contacts whereNotExists(TableLike<?> select) {
        return where(DSL.notExists(select));
    }
}
