/*
 * This file is generated by jOOQ.
 */
package com.ogoma.marketing.infrastructure.jooq.tables;


import com.ogoma.marketing.infrastructure.jooq.DefaultSchema;
import com.ogoma.marketing.infrastructure.jooq.Keys;
import com.ogoma.marketing.infrastructure.jooq.tables.records.EmailTemplatesRecord;
import org.jooq.*;
import org.jooq.impl.DSL;
import org.jooq.impl.Internal;
import org.jooq.impl.SQLDataType;
import org.jooq.impl.TableImpl;

import java.time.OffsetDateTime;
import java.util.Collection;
import java.util.UUID;


/**
 * This class is generated by jOOQ.
 */
@SuppressWarnings({ "all", "unchecked", "rawtypes", "this-escape" })
public class EmailTemplates extends TableImpl<EmailTemplatesRecord> {

    private static final long serialVersionUID = 1L;

    /**
     * The reference instance of <code>email_templates</code>
     */
    public static final EmailTemplates EMAIL_TEMPLATES = new EmailTemplates();

    /**
     * The class holding records for this type
     */
    @Override
    public Class<EmailTemplatesRecord> getRecordType() {
        return EmailTemplatesRecord.class;
    }

    /**
     * The column <code>email_templates.id</code>.
     */
    public final TableField<EmailTemplatesRecord, UUID> ID = createField(DSL.name("id"), SQLDataType.UUID.nullable(false), this, "");

    /**
     * The column <code>email_templates.created_at</code>.
     */
    public final TableField<EmailTemplatesRecord, OffsetDateTime> CREATED_AT = createField(DSL.name("created_at"), SQLDataType.TIMESTAMPWITHTIMEZONE(6), this, "");

    /**
     * The column <code>email_templates.name</code>.
     */
    public final TableField<EmailTemplatesRecord, String> NAME = createField(DSL.name("name"), SQLDataType.VARCHAR, this, "");

    /**
     * The column <code>email_templates.updated_at</code>.
     */
    public final TableField<EmailTemplatesRecord, OffsetDateTime> UPDATED_AT = createField(DSL.name("updated_at"), SQLDataType.TIMESTAMPWITHTIMEZONE(6), this, "");

    /**
     * The column <code>email_templates.email_template</code>.
     */
    public final TableField<EmailTemplatesRecord, JSON> EMAIL_TEMPLATE = createField(DSL.name("email_template"), SQLDataType.JSON, this, "");

    /**
     * The column <code>email_templates.version</code>.
     */
    public final TableField<EmailTemplatesRecord, Long> VERSION = createField(DSL.name("version"), SQLDataType.BIGINT, this, "");

    /**
     * The column <code>email_templates.created_by</code>.
     */
    public final TableField<EmailTemplatesRecord, String> CREATED_BY = createField(DSL.name("created_by"), SQLDataType.VARCHAR, this, "");

    /**
     * The column <code>email_templates.last_updated_by</code>.
     */
    public final TableField<EmailTemplatesRecord, String> LAST_UPDATED_BY = createField(DSL.name("last_updated_by"), SQLDataType.VARCHAR, this, "");

    private EmailTemplates(Name alias, Table<EmailTemplatesRecord> aliased) {
        this(alias, aliased, (Field<?>[]) null, null);
    }

    private EmailTemplates(Name alias, Table<EmailTemplatesRecord> aliased, Field<?>[] parameters, Condition where) {
        super(alias, null, aliased, parameters, DSL.comment(""), TableOptions.table(), where);
    }

    /**
     * Create an aliased <code>email_templates</code> table reference
     */
    public EmailTemplates(String alias) {
        this(DSL.name(alias), EMAIL_TEMPLATES);
    }

    /**
     * Create an aliased <code>email_templates</code> table reference
     */
    public EmailTemplates(Name alias) {
        this(alias, EMAIL_TEMPLATES);
    }

    /**
     * Create a <code>email_templates</code> table reference
     */
    public EmailTemplates() {
        this(DSL.name("email_templates"), null);
    }

    @Override
    public Schema getSchema() {
        return aliased() ? null : DefaultSchema.DEFAULT_SCHEMA;
    }

    @Override
    public UniqueKey<EmailTemplatesRecord> getPrimaryKey() {
        return Keys.EMAIL_TEMPLATES_PKEY;
    }

    @Override
    public EmailTemplates as(String alias) {
        return new EmailTemplates(DSL.name(alias), this);
    }

    @Override
    public EmailTemplates as(Name alias) {
        return new EmailTemplates(alias, this);
    }

    @Override
    public EmailTemplates as(Table<?> alias) {
        return new EmailTemplates(alias.getQualifiedName(), this);
    }

    /**
     * Rename this table
     */
    @Override
    public EmailTemplates rename(String name) {
        return new EmailTemplates(DSL.name(name), null);
    }

    /**
     * Rename this table
     */
    @Override
    public EmailTemplates rename(Name name) {
        return new EmailTemplates(name, null);
    }

    /**
     * Rename this table
     */
    @Override
    public EmailTemplates rename(Table<?> name) {
        return new EmailTemplates(name.getQualifiedName(), null);
    }

    /**
     * Create an inline derived table from this table
     */
    @Override
    public EmailTemplates where(Condition condition) {
        return new EmailTemplates(getQualifiedName(), aliased() ? this : null, null, Internal.condition(this, condition));
    }

    /**
     * Create an inline derived table from this table
     */
    @Override
    public EmailTemplates where(Collection<? extends Condition> conditions) {
        return where(DSL.and(conditions));
    }

    /**
     * Create an inline derived table from this table
     */
    @Override
    public EmailTemplates where(Condition... conditions) {
        return where(DSL.and(conditions));
    }

    /**
     * Create an inline derived table from this table
     */
    @Override
    public EmailTemplates where(Field<Boolean> condition) {
        return where(DSL.condition(condition));
    }

    /**
     * Create an inline derived table from this table
     */
    @Override
    @PlainSQL
    public EmailTemplates where(SQL condition) {
        return where(DSL.condition(condition));
    }

    /**
     * Create an inline derived table from this table
     */
    @Override
    @PlainSQL
    public EmailTemplates where(@Stringly.SQL String condition) {
        return where(DSL.condition(condition));
    }

    /**
     * Create an inline derived table from this table
     */
    @Override
    @PlainSQL
    public EmailTemplates where(@Stringly.SQL String condition, Object... binds) {
        return where(DSL.condition(condition, binds));
    }

    /**
     * Create an inline derived table from this table
     */
    @Override
    @PlainSQL
    public EmailTemplates where(@Stringly.SQL String condition, QueryPart... parts) {
        return where(DSL.condition(condition, parts));
    }

    /**
     * Create an inline derived table from this table
     */
    @Override
    public EmailTemplates whereExists(TableLike<?> select) {
        return where(DSL.exists(select));
    }

    /**
     * Create an inline derived table from this table
     */
    @Override
    public EmailTemplates whereNotExists(TableLike<?> select) {
        return where(DSL.notExists(select));
    }
}
