/*
 * This file is generated by jOOQ.
 */
package com.ogoma.marketing.infrastructure.jooq.tables;


import com.ogoma.marketing.infrastructure.jooq.DefaultSchema;
import com.ogoma.marketing.infrastructure.jooq.Keys;
import com.ogoma.marketing.infrastructure.jooq.tables.records.MessageOutboxRecord;
import org.jooq.*;
import org.jooq.impl.DSL;
import org.jooq.impl.Internal;
import org.jooq.impl.SQLDataType;
import org.jooq.impl.TableImpl;

import java.time.OffsetDateTime;
import java.util.Collection;
import java.util.UUID;


/**
 * This class is generated by jOOQ.
 */
@SuppressWarnings({ "all", "unchecked", "rawtypes", "this-escape" })
public class MessageOutbox extends TableImpl<MessageOutboxRecord> {

    private static final long serialVersionUID = 1L;

    /**
     * The reference instance of <code>message_outbox</code>
     */
    public static final MessageOutbox MESSAGE_OUTBOX = new MessageOutbox();

    /**
     * The class holding records for this type
     */
    @Override
    public Class<MessageOutboxRecord> getRecordType() {
        return MessageOutboxRecord.class;
    }

    /**
     * The column <code>message_outbox.id</code>.
     */
    public final TableField<MessageOutboxRecord, UUID> ID = createField(DSL.name("id"), SQLDataType.UUID.nullable(false), this, "");

    /**
     * The column <code>message_outbox.aggregate_type</code>.
     */
    public final TableField<MessageOutboxRecord, String> AGGREGATE_TYPE = createField(DSL.name("aggregate_type"), SQLDataType.VARCHAR.nullable(false), this, "");

    /**
     * The column <code>message_outbox.aggregate_id</code>.
     */
    public final TableField<MessageOutboxRecord, UUID> AGGREGATE_ID = createField(DSL.name("aggregate_id"), SQLDataType.UUID.nullable(false), this, "");

    /**
     * The column <code>message_outbox.event_type</code>.
     */
    public final TableField<MessageOutboxRecord, String> EVENT_TYPE = createField(DSL.name("event_type"), SQLDataType.VARCHAR.nullable(false), this, "");

    /**
     * The column <code>message_outbox.event_version</code>.
     */
    public final TableField<MessageOutboxRecord, String> EVENT_VERSION = createField(DSL.name("event_version"), SQLDataType.VARCHAR.nullable(false), this, "");

    /**
     * The column <code>message_outbox.event_name</code>.
     */
    public final TableField<MessageOutboxRecord, String> EVENT_NAME = createField(DSL.name("event_name"), SQLDataType.VARCHAR.nullable(false), this, "");

    /**
     * The column <code>message_outbox.payload</code>.
     */
    public final TableField<MessageOutboxRecord, JSONB> PAYLOAD = createField(DSL.name("payload"), SQLDataType.JSONB.nullable(false), this, "");

    /**
     * The column <code>message_outbox.created_at</code>.
     */
    public final TableField<MessageOutboxRecord, OffsetDateTime> CREATED_AT = createField(DSL.name("created_at"), SQLDataType.TIMESTAMPWITHTIMEZONE(6).nullable(false), this, "");

    /**
     * The column <code>message_outbox.processed</code>.
     */
    public final TableField<MessageOutboxRecord, Boolean> PROCESSED = createField(DSL.name("processed"), SQLDataType.BOOLEAN.nullable(false).defaultValue(DSL.field(DSL.raw("false"), SQLDataType.BOOLEAN)), this, "");

    /**
     * The column <code>message_outbox.processed_at</code>.
     */
    public final TableField<MessageOutboxRecord, OffsetDateTime> PROCESSED_AT = createField(DSL.name("processed_at"), SQLDataType.TIMESTAMPWITHTIMEZONE(6), this, "");

    /**
     * The column <code>message_outbox.version</code>.
     */
    public final TableField<MessageOutboxRecord, Long> VERSION = createField(DSL.name("version"), SQLDataType.BIGINT.nullable(false), this, "");

    private MessageOutbox(Name alias, Table<MessageOutboxRecord> aliased) {
        this(alias, aliased, (Field<?>[]) null, null);
    }

    private MessageOutbox(Name alias, Table<MessageOutboxRecord> aliased, Field<?>[] parameters, Condition where) {
        super(alias, null, aliased, parameters, DSL.comment(""), TableOptions.table(), where);
    }

    /**
     * Create an aliased <code>message_outbox</code> table reference
     */
    public MessageOutbox(String alias) {
        this(DSL.name(alias), MESSAGE_OUTBOX);
    }

    /**
     * Create an aliased <code>message_outbox</code> table reference
     */
    public MessageOutbox(Name alias) {
        this(alias, MESSAGE_OUTBOX);
    }

    /**
     * Create a <code>message_outbox</code> table reference
     */
    public MessageOutbox() {
        this(DSL.name("message_outbox"), null);
    }

    @Override
    public Schema getSchema() {
        return aliased() ? null : DefaultSchema.DEFAULT_SCHEMA;
    }

    @Override
    public UniqueKey<MessageOutboxRecord> getPrimaryKey() {
        return Keys.MESSAGE_OUTBOX_PKEY;
    }

    @Override
    public MessageOutbox as(String alias) {
        return new MessageOutbox(DSL.name(alias), this);
    }

    @Override
    public MessageOutbox as(Name alias) {
        return new MessageOutbox(alias, this);
    }

    @Override
    public MessageOutbox as(Table<?> alias) {
        return new MessageOutbox(alias.getQualifiedName(), this);
    }

    /**
     * Rename this table
     */
    @Override
    public MessageOutbox rename(String name) {
        return new MessageOutbox(DSL.name(name), null);
    }

    /**
     * Rename this table
     */
    @Override
    public MessageOutbox rename(Name name) {
        return new MessageOutbox(name, null);
    }

    /**
     * Rename this table
     */
    @Override
    public MessageOutbox rename(Table<?> name) {
        return new MessageOutbox(name.getQualifiedName(), null);
    }

    /**
     * Create an inline derived table from this table
     */
    @Override
    public MessageOutbox where(Condition condition) {
        return new MessageOutbox(getQualifiedName(), aliased() ? this : null, null, Internal.condition(this, condition));
    }

    /**
     * Create an inline derived table from this table
     */
    @Override
    public MessageOutbox where(Collection<? extends Condition> conditions) {
        return where(DSL.and(conditions));
    }

    /**
     * Create an inline derived table from this table
     */
    @Override
    public MessageOutbox where(Condition... conditions) {
        return where(DSL.and(conditions));
    }

    /**
     * Create an inline derived table from this table
     */
    @Override
    public MessageOutbox where(Field<Boolean> condition) {
        return where(DSL.condition(condition));
    }

    /**
     * Create an inline derived table from this table
     */
    @Override
    @PlainSQL
    public MessageOutbox where(SQL condition) {
        return where(DSL.condition(condition));
    }

    /**
     * Create an inline derived table from this table
     */
    @Override
    @PlainSQL
    public MessageOutbox where(@Stringly.SQL String condition) {
        return where(DSL.condition(condition));
    }

    /**
     * Create an inline derived table from this table
     */
    @Override
    @PlainSQL
    public MessageOutbox where(@Stringly.SQL String condition, Object... binds) {
        return where(DSL.condition(condition, binds));
    }

    /**
     * Create an inline derived table from this table
     */
    @Override
    @PlainSQL
    public MessageOutbox where(@Stringly.SQL String condition, QueryPart... parts) {
        return where(DSL.condition(condition, parts));
    }

    /**
     * Create an inline derived table from this table
     */
    @Override
    public MessageOutbox whereExists(TableLike<?> select) {
        return where(DSL.exists(select));
    }

    /**
     * Create an inline derived table from this table
     */
    @Override
    public MessageOutbox whereNotExists(TableLike<?> select) {
        return where(DSL.notExists(select));
    }
}
