/*
 * This file is generated by jOOQ.
 */
package com.ogoma.marketing.infrastructure.jooq.tables;


import com.ogoma.marketing.infrastructure.jooq.DefaultSchema;
import com.ogoma.marketing.infrastructure.jooq.Keys;
import com.ogoma.marketing.infrastructure.jooq.tables.CampaignSegments.CampaignSegmentsPath;
import com.ogoma.marketing.infrastructure.jooq.tables.Campaigns.CampaignsPath;
import com.ogoma.marketing.infrastructure.jooq.tables.records.SegmentsRecord;

import java.time.OffsetDateTime;
import java.util.Collection;
import java.util.UUID;

import org.jooq.Condition;
import org.jooq.Field;
import org.jooq.ForeignKey;
import org.jooq.InverseForeignKey;
import org.jooq.JSONB;
import org.jooq.Name;
import org.jooq.Path;
import org.jooq.PlainSQL;
import org.jooq.QueryPart;
import org.jooq.Record;
import org.jooq.SQL;
import org.jooq.Schema;
import org.jooq.Stringly;
import org.jooq.Table;
import org.jooq.TableField;
import org.jooq.TableLike;
import org.jooq.TableOptions;
import org.jooq.UniqueKey;
import org.jooq.impl.DSL;
import org.jooq.impl.Internal;
import org.jooq.impl.SQLDataType;
import org.jooq.impl.TableImpl;


/**
 * This class is generated by jOOQ.
 */
@SuppressWarnings({ "all", "unchecked", "rawtypes", "this-escape" })
public class Segments extends TableImpl<SegmentsRecord> {

    private static final long serialVersionUID = 1L;

    /**
     * The reference instance of <code>segments</code>
     */
    public static final Segments SEGMENTS = new Segments();

    /**
     * The class holding records for this type
     */
    @Override
    public Class<SegmentsRecord> getRecordType() {
        return SegmentsRecord.class;
    }

    /**
     * The column <code>segments.id</code>.
     */
    public final TableField<SegmentsRecord, UUID> ID = createField(DSL.name("id"), SQLDataType.UUID.nullable(false), this, "");

    /**
     * The column <code>segments.name</code>.
     */
    public final TableField<SegmentsRecord, String> NAME = createField(DSL.name("name"), SQLDataType.VARCHAR(255).nullable(false), this, "");

    /**
     * The column <code>segments.ruleset</code>.
     */
    public final TableField<SegmentsRecord, JSONB> RULESET = createField(DSL.name("ruleset"), SQLDataType.JSONB.nullable(false), this, "");

    /**
     * The column <code>segments.created_at</code>.
     */
    public final TableField<SegmentsRecord, OffsetDateTime> CREATED_AT = createField(DSL.name("created_at"), SQLDataType.TIMESTAMPWITHTIMEZONE(6).nullable(false), this, "");

    /**
     * The column <code>segments.created_by</code>.
     */
    public final TableField<SegmentsRecord, String> CREATED_BY = createField(DSL.name("created_by"), SQLDataType.VARCHAR(255).nullable(false), this, "");

    /**
     * The column <code>segments.last_updated_at</code>.
     */
    public final TableField<SegmentsRecord, OffsetDateTime> LAST_UPDATED_AT = createField(DSL.name("last_updated_at"), SQLDataType.TIMESTAMPWITHTIMEZONE(6).nullable(false), this, "");

    /**
     * The column <code>segments.last_updated_by</code>.
     */
    public final TableField<SegmentsRecord, String> LAST_UPDATED_BY = createField(DSL.name("last_updated_by"), SQLDataType.VARCHAR(255).nullable(false), this, "");

    /**
     * The column <code>segments.version</code>.
     */
    public final TableField<SegmentsRecord, Long> VERSION = createField(DSL.name("version"), SQLDataType.BIGINT.nullable(false).defaultValue(DSL.field(DSL.raw("0"), SQLDataType.BIGINT)), this, "");

    /**
     * The column <code>segments.description</code>.
     */
    public final TableField<SegmentsRecord, String> DESCRIPTION = createField(DSL.name("description"), SQLDataType.VARCHAR, this, "");

    private Segments(Name alias, Table<SegmentsRecord> aliased) {
        this(alias, aliased, (Field<?>[]) null, null);
    }

    private Segments(Name alias, Table<SegmentsRecord> aliased, Field<?>[] parameters, Condition where) {
        super(alias, null, aliased, parameters, DSL.comment(""), TableOptions.table(), where);
    }

    /**
     * Create an aliased <code>segments</code> table reference
     */
    public Segments(String alias) {
        this(DSL.name(alias), SEGMENTS);
    }

    /**
     * Create an aliased <code>segments</code> table reference
     */
    public Segments(Name alias) {
        this(alias, SEGMENTS);
    }

    /**
     * Create a <code>segments</code> table reference
     */
    public Segments() {
        this(DSL.name("segments"), null);
    }

    public <O extends Record> Segments(Table<O> path, ForeignKey<O, SegmentsRecord> childPath, InverseForeignKey<O, SegmentsRecord> parentPath) {
        super(path, childPath, parentPath, SEGMENTS);
    }

    /**
     * A subtype implementing {@link Path} for simplified path-based joins.
     */
    public static class SegmentsPath extends Segments implements Path<SegmentsRecord> {

        private static final long serialVersionUID = 1L;
        public <O extends Record> SegmentsPath(Table<O> path, ForeignKey<O, SegmentsRecord> childPath, InverseForeignKey<O, SegmentsRecord> parentPath) {
            super(path, childPath, parentPath);
        }
        private SegmentsPath(Name alias, Table<SegmentsRecord> aliased) {
            super(alias, aliased);
        }

        @Override
        public SegmentsPath as(String alias) {
            return new SegmentsPath(DSL.name(alias), this);
        }

        @Override
        public SegmentsPath as(Name alias) {
            return new SegmentsPath(alias, this);
        }

        @Override
        public SegmentsPath as(Table<?> alias) {
            return new SegmentsPath(alias.getQualifiedName(), this);
        }
    }

    @Override
    public Schema getSchema() {
        return aliased() ? null : DefaultSchema.DEFAULT_SCHEMA;
    }

    @Override
    public UniqueKey<SegmentsRecord> getPrimaryKey() {
        return Keys.SEGMENTS_PKEY;
    }

    private transient CampaignSegmentsPath _campaignSegments;

    /**
     * Get the implicit to-many join path to the <code>campaign_segments</code>
     * table
     */
    public CampaignSegmentsPath campaignSegments() {
        if (_campaignSegments == null)
            _campaignSegments = new CampaignSegmentsPath(this, null, Keys.CAMPAIGN_SEGMENTS__CAMPAIGN_SEGMENTS_SEGMENT_ID_FKEY.getInverseKey());

        return _campaignSegments;
    }

    /**
     * Get the implicit many-to-many join path to the <code>campaigns</code>
     * table
     */
    public CampaignsPath campaigns() {
        return campaignSegments().campaigns();
    }

    @Override
    public Segments as(String alias) {
        return new Segments(DSL.name(alias), this);
    }

    @Override
    public Segments as(Name alias) {
        return new Segments(alias, this);
    }

    @Override
    public Segments as(Table<?> alias) {
        return new Segments(alias.getQualifiedName(), this);
    }

    /**
     * Rename this table
     */
    @Override
    public Segments rename(String name) {
        return new Segments(DSL.name(name), null);
    }

    /**
     * Rename this table
     */
    @Override
    public Segments rename(Name name) {
        return new Segments(name, null);
    }

    /**
     * Rename this table
     */
    @Override
    public Segments rename(Table<?> name) {
        return new Segments(name.getQualifiedName(), null);
    }

    /**
     * Create an inline derived table from this table
     */
    @Override
    public Segments where(Condition condition) {
        return new Segments(getQualifiedName(), aliased() ? this : null, null, Internal.condition(this, condition));
    }

    /**
     * Create an inline derived table from this table
     */
    @Override
    public Segments where(Collection<? extends Condition> conditions) {
        return where(DSL.and(conditions));
    }

    /**
     * Create an inline derived table from this table
     */
    @Override
    public Segments where(Condition... conditions) {
        return where(DSL.and(conditions));
    }

    /**
     * Create an inline derived table from this table
     */
    @Override
    public Segments where(Field<Boolean> condition) {
        return where(DSL.condition(condition));
    }

    /**
     * Create an inline derived table from this table
     */
    @Override
    @PlainSQL
    public Segments where(SQL condition) {
        return where(DSL.condition(condition));
    }

    /**
     * Create an inline derived table from this table
     */
    @Override
    @PlainSQL
    public Segments where(@Stringly.SQL String condition) {
        return where(DSL.condition(condition));
    }

    /**
     * Create an inline derived table from this table
     */
    @Override
    @PlainSQL
    public Segments where(@Stringly.SQL String condition, Object... binds) {
        return where(DSL.condition(condition, binds));
    }

    /**
     * Create an inline derived table from this table
     */
    @Override
    @PlainSQL
    public Segments where(@Stringly.SQL String condition, QueryPart... parts) {
        return where(DSL.condition(condition, parts));
    }

    /**
     * Create an inline derived table from this table
     */
    @Override
    public Segments whereExists(TableLike<?> select) {
        return where(DSL.exists(select));
    }

    /**
     * Create an inline derived table from this table
     */
    @Override
    public Segments whereNotExists(TableLike<?> select) {
        return where(DSL.notExists(select));
    }
}
