/*
 * This file is generated by jOOQ.
 */
package com.ogoma.marketing.infrastructure.jooq.tables;


import com.ogoma.marketing.infrastructure.jooq.DefaultSchema;
import com.ogoma.marketing.infrastructure.jooq.Keys;
import com.ogoma.marketing.infrastructure.jooq.tables.records.SmsTemplatesRecord;

import java.time.OffsetDateTime;
import java.util.Collection;
import java.util.UUID;

import org.jooq.Condition;
import org.jooq.Field;
import org.jooq.Name;
import org.jooq.PlainSQL;
import org.jooq.QueryPart;
import org.jooq.SQL;
import org.jooq.Schema;
import org.jooq.Stringly;
import org.jooq.Table;
import org.jooq.TableField;
import org.jooq.TableLike;
import org.jooq.TableOptions;
import org.jooq.UniqueKey;
import org.jooq.impl.DSL;
import org.jooq.impl.Internal;
import org.jooq.impl.SQLDataType;
import org.jooq.impl.TableImpl;


/**
 * This class is generated by jOOQ.
 */
@SuppressWarnings({ "all", "unchecked", "rawtypes", "this-escape" })
public class SmsTemplates extends TableImpl<SmsTemplatesRecord> {

    private static final long serialVersionUID = 1L;

    /**
     * The reference instance of <code>sms_templates</code>
     */
    public static final SmsTemplates SMS_TEMPLATES = new SmsTemplates();

    /**
     * The class holding records for this type
     */
    @Override
    public Class<SmsTemplatesRecord> getRecordType() {
        return SmsTemplatesRecord.class;
    }

    /**
     * The column <code>sms_templates.id</code>.
     */
    public final TableField<SmsTemplatesRecord, UUID> ID = createField(DSL.name("id"), SQLDataType.UUID.nullable(false), this, "");

    /**
     * The column <code>sms_templates.content</code>.
     */
    public final TableField<SmsTemplatesRecord, String> CONTENT = createField(DSL.name("content"), SQLDataType.CLOB, this, "");

    /**
     * The column <code>sms_templates.name</code>.
     */
    public final TableField<SmsTemplatesRecord, String> NAME = createField(DSL.name("name"), SQLDataType.VARCHAR, this, "");

    /**
     * The column <code>sms_templates.version</code>.
     */
    public final TableField<SmsTemplatesRecord, Long> VERSION = createField(DSL.name("version"), SQLDataType.BIGINT, this, "");

    /**
     * The column <code>sms_templates.description</code>.
     */
    public final TableField<SmsTemplatesRecord, String> DESCRIPTION = createField(DSL.name("description"), SQLDataType.CLOB, this, "");

    /**
     * The column <code>sms_templates.created_at</code>.
     */
    public final TableField<SmsTemplatesRecord, OffsetDateTime> CREATED_AT = createField(DSL.name("created_at"), SQLDataType.TIMESTAMPWITHTIMEZONE(6), this, "");

    /**
     * The column <code>sms_templates.updated_by</code>.
     */
    public final TableField<SmsTemplatesRecord, String> UPDATED_BY = createField(DSL.name("updated_by"), SQLDataType.VARCHAR, this, "");

    /**
     * The column <code>sms_templates.created_by</code>.
     */
    public final TableField<SmsTemplatesRecord, String> CREATED_BY = createField(DSL.name("created_by"), SQLDataType.VARCHAR, this, "");

    /**
     * The column <code>sms_templates.updated_at</code>.
     */
    public final TableField<SmsTemplatesRecord, OffsetDateTime> UPDATED_AT = createField(DSL.name("updated_at"), SQLDataType.TIMESTAMPWITHTIMEZONE(6), this, "");

    private SmsTemplates(Name alias, Table<SmsTemplatesRecord> aliased) {
        this(alias, aliased, (Field<?>[]) null, null);
    }

    private SmsTemplates(Name alias, Table<SmsTemplatesRecord> aliased, Field<?>[] parameters, Condition where) {
        super(alias, null, aliased, parameters, DSL.comment(""), TableOptions.table(), where);
    }

    /**
     * Create an aliased <code>sms_templates</code> table reference
     */
    public SmsTemplates(String alias) {
        this(DSL.name(alias), SMS_TEMPLATES);
    }

    /**
     * Create an aliased <code>sms_templates</code> table reference
     */
    public SmsTemplates(Name alias) {
        this(alias, SMS_TEMPLATES);
    }

    /**
     * Create a <code>sms_templates</code> table reference
     */
    public SmsTemplates() {
        this(DSL.name("sms_templates"), null);
    }

    @Override
    public Schema getSchema() {
        return aliased() ? null : DefaultSchema.DEFAULT_SCHEMA;
    }

    @Override
    public UniqueKey<SmsTemplatesRecord> getPrimaryKey() {
        return Keys.SMS_TEMPLATES_PKEY;
    }

    @Override
    public SmsTemplates as(String alias) {
        return new SmsTemplates(DSL.name(alias), this);
    }

    @Override
    public SmsTemplates as(Name alias) {
        return new SmsTemplates(alias, this);
    }

    @Override
    public SmsTemplates as(Table<?> alias) {
        return new SmsTemplates(alias.getQualifiedName(), this);
    }

    /**
     * Rename this table
     */
    @Override
    public SmsTemplates rename(String name) {
        return new SmsTemplates(DSL.name(name), null);
    }

    /**
     * Rename this table
     */
    @Override
    public SmsTemplates rename(Name name) {
        return new SmsTemplates(name, null);
    }

    /**
     * Rename this table
     */
    @Override
    public SmsTemplates rename(Table<?> name) {
        return new SmsTemplates(name.getQualifiedName(), null);
    }

    /**
     * Create an inline derived table from this table
     */
    @Override
    public SmsTemplates where(Condition condition) {
        return new SmsTemplates(getQualifiedName(), aliased() ? this : null, null, Internal.condition(this, condition));
    }

    /**
     * Create an inline derived table from this table
     */
    @Override
    public SmsTemplates where(Collection<? extends Condition> conditions) {
        return where(DSL.and(conditions));
    }

    /**
     * Create an inline derived table from this table
     */
    @Override
    public SmsTemplates where(Condition... conditions) {
        return where(DSL.and(conditions));
    }

    /**
     * Create an inline derived table from this table
     */
    @Override
    public SmsTemplates where(Field<Boolean> condition) {
        return where(DSL.condition(condition));
    }

    /**
     * Create an inline derived table from this table
     */
    @Override
    @PlainSQL
    public SmsTemplates where(SQL condition) {
        return where(DSL.condition(condition));
    }

    /**
     * Create an inline derived table from this table
     */
    @Override
    @PlainSQL
    public SmsTemplates where(@Stringly.SQL String condition) {
        return where(DSL.condition(condition));
    }

    /**
     * Create an inline derived table from this table
     */
    @Override
    @PlainSQL
    public SmsTemplates where(@Stringly.SQL String condition, Object... binds) {
        return where(DSL.condition(condition, binds));
    }

    /**
     * Create an inline derived table from this table
     */
    @Override
    @PlainSQL
    public SmsTemplates where(@Stringly.SQL String condition, QueryPart... parts) {
        return where(DSL.condition(condition, parts));
    }

    /**
     * Create an inline derived table from this table
     */
    @Override
    public SmsTemplates whereExists(TableLike<?> select) {
        return where(DSL.exists(select));
    }

    /**
     * Create an inline derived table from this table
     */
    @Override
    public SmsTemplates whereNotExists(TableLike<?> select) {
        return where(DSL.notExists(select));
    }
}
