/*
 * This file is generated by jOOQ.
 */
package com.ogoma.marketing.infrastructure.jooq.tables.records;


import com.ogoma.marketing.infrastructure.jooq.tables.AudienceMembership;

import java.time.OffsetDateTime;
import java.util.UUID;

import org.jooq.Record1;
import org.jooq.impl.UpdatableRecordImpl;


/**
 * This class is generated by jOOQ.
 */
@SuppressWarnings({ "all", "unchecked", "rawtypes", "this-escape" })
public class AudienceMembershipRecord extends UpdatableRecordImpl<AudienceMembershipRecord> {

    private static final long serialVersionUID = 1L;

    /**
     * Setter for <code>audience_membership.id</code>.
     */
    public void setId(UUID value) {
        set(0, value);
    }

    /**
     * Getter for <code>audience_membership.id</code>.
     */
    public UUID getId() {
        return (UUID) get(0);
    }

    /**
     * Setter for <code>audience_membership.contact_id</code>.
     */
    public void setContactId(UUID value) {
        set(1, value);
    }

    /**
     * Getter for <code>audience_membership.contact_id</code>.
     */
    public UUID getContactId() {
        return (UUID) get(1);
    }

    /**
     * Setter for <code>audience_membership.audience_id</code>.
     */
    public void setAudienceId(UUID value) {
        set(2, value);
    }

    /**
     * Getter for <code>audience_membership.audience_id</code>.
     */
    public UUID getAudienceId() {
        return (UUID) get(2);
    }

    /**
     * Setter for <code>audience_membership.joined_at</code>.
     */
    public void setJoinedAt(OffsetDateTime value) {
        set(3, value);
    }

    /**
     * Getter for <code>audience_membership.joined_at</code>.
     */
    public OffsetDateTime getJoinedAt() {
        return (OffsetDateTime) get(3);
    }

    /**
     * Setter for <code>audience_membership.version</code>.
     */
    public void setVersion(Long value) {
        set(4, value);
    }

    /**
     * Getter for <code>audience_membership.version</code>.
     */
    public Long getVersion() {
        return (Long) get(4);
    }

    // -------------------------------------------------------------------------
    // Primary key information
    // -------------------------------------------------------------------------

    @Override
    public Record1<UUID> key() {
        return (Record1) super.key();
    }

    // -------------------------------------------------------------------------
    // Constructors
    // -------------------------------------------------------------------------

    /**
     * Create a detached AudienceMembershipRecord
     */
    public AudienceMembershipRecord() {
        super(AudienceMembership.AUDIENCE_MEMBERSHIP);
    }

    /**
     * Create a detached, initialised AudienceMembershipRecord
     */
    public AudienceMembershipRecord(UUID id, UUID contactId, UUID audienceId, OffsetDateTime joinedAt, Long version) {
        super(AudienceMembership.AUDIENCE_MEMBERSHIP);

        setId(id);
        setContactId(contactId);
        setAudienceId(audienceId);
        setJoinedAt(joinedAt);
        setVersion(version);
        resetTouchedOnNotNull();
    }
}
