/*
 * This file is generated by jOOQ.
 */
package com.ogoma.marketing.infrastructure.jooq.tables.records;


import com.ogoma.marketing.infrastructure.jooq.tables.Audiences;

import java.time.OffsetDateTime;
import java.util.UUID;

import org.jooq.JSONB;
import org.jooq.Record1;
import org.jooq.impl.UpdatableRecordImpl;


/**
 * This class is generated by jOOQ.
 */
@SuppressWarnings({ "all", "unchecked", "rawtypes", "this-escape" })
public class AudiencesRecord extends UpdatableRecordImpl<AudiencesRecord> {

    private static final long serialVersionUID = 1L;

    /**
     * Setter for <code>audiences.id</code>.
     */
    public void setId(UUID value) {
        set(0, value);
    }

    /**
     * Getter for <code>audiences.id</code>.
     */
    public UUID getId() {
        return (UUID) get(0);
    }

    /**
     * Setter for <code>audiences.name</code>.
     */
    public void setName(String value) {
        set(1, value);
    }

    /**
     * Getter for <code>audiences.name</code>.
     */
    public String getName() {
        return (String) get(1);
    }

    /**
     * Setter for <code>audiences.version</code>.
     */
    public void setVersion(Long value) {
        set(2, value);
    }

    /**
     * Getter for <code>audiences.version</code>.
     */
    public Long getVersion() {
        return (Long) get(2);
    }

    /**
     * Setter for <code>audiences.created_at</code>.
     */
    public void setCreatedAt(OffsetDateTime value) {
        set(3, value);
    }

    /**
     * Getter for <code>audiences.created_at</code>.
     */
    public OffsetDateTime getCreatedAt() {
        return (OffsetDateTime) get(3);
    }

    /**
     * Setter for <code>audiences.updated_at</code>.
     */
    public void setUpdatedAt(OffsetDateTime value) {
        set(4, value);
    }

    /**
     * Getter for <code>audiences.updated_at</code>.
     */
    public OffsetDateTime getUpdatedAt() {
        return (OffsetDateTime) get(4);
    }

    /**
     * Setter for <code>audiences.created_by</code>.
     */
    public void setCreatedBy(String value) {
        set(5, value);
    }

    /**
     * Getter for <code>audiences.created_by</code>.
     */
    public String getCreatedBy() {
        return (String) get(5);
    }

    /**
     * Setter for <code>audiences.updated_by</code>.
     */
    public void setUpdatedBy(String value) {
        set(6, value);
    }

    /**
     * Getter for <code>audiences.updated_by</code>.
     */
    public String getUpdatedBy() {
        return (String) get(6);
    }

    /**
     * Setter for <code>audiences.type</code>.
     */
    public void setType(String value) {
        set(7, value);
    }

    /**
     * Getter for <code>audiences.type</code>.
     */
    public String getType() {
        return (String) get(7);
    }

    /**
     * Setter for <code>audiences.ruleset</code>.
     */
    public void setRuleset(JSONB value) {
        set(8, value);
    }

    /**
     * Getter for <code>audiences.ruleset</code>.
     */
    public JSONB getRuleset() {
        return (JSONB) get(8);
    }

    // -------------------------------------------------------------------------
    // Primary key information
    // -------------------------------------------------------------------------

    @Override
    public Record1<UUID> key() {
        return (Record1) super.key();
    }

    // -------------------------------------------------------------------------
    // Constructors
    // -------------------------------------------------------------------------

    /**
     * Create a detached AudiencesRecord
     */
    public AudiencesRecord() {
        super(Audiences.AUDIENCES);
    }

    /**
     * Create a detached, initialised AudiencesRecord
     */
    public AudiencesRecord(UUID id, String name, Long version, OffsetDateTime createdAt, OffsetDateTime updatedAt, String createdBy, String updatedBy, String type, JSONB ruleset) {
        super(Audiences.AUDIENCES);

        setId(id);
        setName(name);
        setVersion(version);
        setCreatedAt(createdAt);
        setUpdatedAt(updatedAt);
        setCreatedBy(createdBy);
        setUpdatedBy(updatedBy);
        setType(type);
        setRuleset(ruleset);
        resetTouchedOnNotNull();
    }
}
