/*
 * This file is generated by jOOQ.
 */
package com.ogoma.marketing.infrastructure.jooq.tables.records;


import com.ogoma.marketing.infrastructure.jooq.tables.CampaignChannels;

import java.util.UUID;

import org.jooq.Record2;
import org.jooq.impl.UpdatableRecordImpl;


/**
 * This class is generated by jOOQ.
 */
@SuppressWarnings({ "all", "unchecked", "rawtypes", "this-escape" })
public class CampaignChannelsRecord extends UpdatableRecordImpl<CampaignChannelsRecord> {

    private static final long serialVersionUID = 1L;

    /**
     * Setter for <code>campaign_channels.campaign_id</code>.
     */
    public void setCampaignId(UUID value) {
        set(0, value);
    }

    /**
     * Getter for <code>campaign_channels.campaign_id</code>.
     */
    public UUID getCampaignId() {
        return (UUID) get(0);
    }

    /**
     * Setter for <code>campaign_channels.channel</code>.
     */
    public void setChannel(String value) {
        set(1, value);
    }

    /**
     * Getter for <code>campaign_channels.channel</code>.
     */
    public String getChannel() {
        return (String) get(1);
    }

    // -------------------------------------------------------------------------
    // Primary key information
    // -------------------------------------------------------------------------

    @Override
    public Record2<UUID, String> key() {
        return (Record2) super.key();
    }

    // -------------------------------------------------------------------------
    // Constructors
    // -------------------------------------------------------------------------

    /**
     * Create a detached CampaignChannelsRecord
     */
    public CampaignChannelsRecord() {
        super(CampaignChannels.CAMPAIGN_CHANNELS);
    }

    /**
     * Create a detached, initialised CampaignChannelsRecord
     */
    public CampaignChannelsRecord(UUID campaignId, String channel) {
        super(CampaignChannels.CAMPAIGN_CHANNELS);

        setCampaignId(campaignId);
        setChannel(channel);
        resetTouchedOnNotNull();
    }
}
