/*
 * This file is generated by jOOQ.
 */
package com.ogoma.marketing.infrastructure.jooq.tables.records;


import com.ogoma.marketing.infrastructure.jooq.tables.Campaigns;
import org.jooq.JSONB;
import org.jooq.Record1;
import org.jooq.impl.UpdatableRecordImpl;

import java.time.LocalDateTime;
import java.time.OffsetDateTime;
import java.util.UUID;


/**
 * This class is generated by jOOQ.
 */
@SuppressWarnings({ "all", "unchecked", "rawtypes", "this-escape" })
public class CampaignsRecord extends UpdatableRecordImpl<CampaignsRecord> {

    private static final long serialVersionUID = 1L;

    /**
     * Setter for <code>campaigns.id</code>.
     */
    public void setId(UUID value) {
        set(0, value);
    }

    /**
     * Getter for <code>campaigns.id</code>.
     */
    public UUID getId() {
        return (UUID) get(0);
    }

    /**
     * Setter for <code>campaigns.name</code>.
     */
    public void setName(String value) {
        set(1, value);
    }

    /**
     * Getter for <code>campaigns.name</code>.
     */
    public String getName() {
        return (String) get(1);
    }

    /**
     * Setter for <code>campaigns.description</code>.
     */
    public void setDescription(String value) {
        set(2, value);
    }

    /**
     * Getter for <code>campaigns.description</code>.
     */
    public String getDescription() {
        return (String) get(2);
    }

    /**
     * Setter for <code>campaigns.version</code>.
     */
    public void setVersion(Long value) {
        set(3, value);
    }

    /**
     * Getter for <code>campaigns.version</code>.
     */
    public Long getVersion() {
        return (Long) get(3);
    }

    /**
     * Setter for <code>campaigns.configuration</code>.
     */
    public void setConfiguration(JSONB value) {
        set(4, value);
    }

    /**
     * Getter for <code>campaigns.configuration</code>.
     */
    public JSONB getConfiguration() {
        return (JSONB) get(4);
    }

    /**
     * Setter for <code>campaigns.created_by</code>.
     */
    public void setCreatedBy(String value) {
        set(5, value);
    }

    /**
     * Getter for <code>campaigns.created_by</code>.
     */
    public String getCreatedBy() {
        return (String) get(5);
    }

    /**
     * Setter for <code>campaigns.created_at</code>.
     */
    public void setCreatedAt(OffsetDateTime value) {
        set(6, value);
    }

    /**
     * Getter for <code>campaigns.created_at</code>.
     */
    public OffsetDateTime getCreatedAt() {
        return (OffsetDateTime) get(6);
    }

    /**
     * Setter for <code>campaigns.last_updated_at</code>.
     */
    public void setLastUpdatedAt(LocalDateTime value) {
        set(7, value);
    }

    /**
     * Getter for <code>campaigns.last_updated_at</code>.
     */
    public LocalDateTime getLastUpdatedAt() {
        return (LocalDateTime) get(7);
    }

    /**
     * Setter for <code>campaigns.last_updated_by</code>.
     */
    public void setLastUpdatedBy(String value) {
        set(8, value);
    }

    /**
     * Getter for <code>campaigns.last_updated_by</code>.
     */
    public String getLastUpdatedBy() {
        return (String) get(8);
    }

    /**
     * Setter for <code>campaigns.status</code>.
     */
    public void setStatus(String value) {
        set(9, value);
    }

    /**
     * Getter for <code>campaigns.status</code>.
     */
    public String getStatus() {
        return (String) get(9);
    }

    /**
     * Setter for <code>campaigns.sms_template_id</code>.
     */
    public void setSmsTemplateId(UUID value) {
        set(10, value);
    }

    /**
     * Getter for <code>campaigns.sms_template_id</code>.
     */
    public UUID getSmsTemplateId() {
        return (UUID) get(10);
    }

    /**
     * Setter for <code>campaigns.email_template_id</code>.
     */
    public void setEmailTemplateId(UUID value) {
        set(11, value);
    }

    /**
     * Getter for <code>campaigns.email_template_id</code>.
     */
    public UUID getEmailTemplateId() {
        return (UUID) get(11);
    }

    /**
     * Setter for <code>campaigns.channels</code>.
     */
    public void setChannels(String[] value) {
        set(12, value);
    }

    /**
     * Getter for <code>campaigns.channels</code>.
     */
    public String[] getChannels() {
        return (String[]) get(12);
    }

    // -------------------------------------------------------------------------
    // Primary key information
    // -------------------------------------------------------------------------

    @Override
    public Record1<UUID> key() {
        return (Record1) super.key();
    }

    // -------------------------------------------------------------------------
    // Constructors
    // -------------------------------------------------------------------------

    /**
     * Create a detached CampaignsRecord
     */
    public CampaignsRecord() {
        super(Campaigns.CAMPAIGNS);
    }

    /**
     * Create a detached, initialised CampaignsRecord
     */
    public CampaignsRecord(UUID id, String name, String description, Long version, JSONB configuration, String createdBy, OffsetDateTime createdAt, LocalDateTime lastUpdatedAt, String lastUpdatedBy, String status, UUID smsTemplateId, UUID emailTemplateId, String[] channels) {
        super(Campaigns.CAMPAIGNS);

        setId(id);
        setName(name);
        setDescription(description);
        setVersion(version);
        setConfiguration(configuration);
        setCreatedBy(createdBy);
        setCreatedAt(createdAt);
        setLastUpdatedAt(lastUpdatedAt);
        setLastUpdatedBy(lastUpdatedBy);
        setStatus(status);
        setSmsTemplateId(smsTemplateId);
        setEmailTemplateId(emailTemplateId);
        setChannels(channels);
        resetTouchedOnNotNull();
    }
}
