/*
 * This file is generated by jOOQ.
 */
package com.ogoma.marketing.infrastructure.jooq.tables.records;


import com.ogoma.marketing.infrastructure.jooq.tables.CampaignSegments;
import org.jooq.Record2;
import org.jooq.impl.UpdatableRecordImpl;

import java.util.UUID;


/**
 * This class is generated by jOOQ.
 */
@SuppressWarnings({ "all", "unchecked", "rawtypes", "this-escape" })
public class CampaignSegmentsRecord extends UpdatableRecordImpl<CampaignSegmentsRecord> {

    private static final long serialVersionUID = 1L;

    /**
     * Setter for <code>campaign_segments.campaign_id</code>.
     */
    public void setCampaignId(UUID value) {
        set(0, value);
    }

    /**
     * Getter for <code>campaign_segments.campaign_id</code>.
     */
    public UUID getCampaignId() {
        return (UUID) get(0);
    }

    /**
     * Setter for <code>campaign_segments.segment_id</code>.
     */
    public void setSegmentId(UUID value) {
        set(1, value);
    }

    /**
     * Getter for <code>campaign_segments.segment_id</code>.
     */
    public UUID getSegmentId() {
        return (UUID) get(1);
    }

    // -------------------------------------------------------------------------
    // Primary key information
    // -------------------------------------------------------------------------

    @Override
    public Record2<UUID, UUID> key() {
        return (Record2) super.key();
    }

    // -------------------------------------------------------------------------
    // Constructors
    // -------------------------------------------------------------------------

    /**
     * Create a detached CampaignSegmentsRecord
     */
    public CampaignSegmentsRecord() {
        super(CampaignSegments.CAMPAIGN_SEGMENTS);
    }

    /**
     * Create a detached, initialised CampaignSegmentsRecord
     */
    public CampaignSegmentsRecord(UUID campaignId, UUID segmentId) {
        super(CampaignSegments.CAMPAIGN_SEGMENTS);

        setCampaignId(campaignId);
        setSegmentId(segmentId);
        resetTouchedOnNotNull();
    }
}
