/*
 * This file is generated by jOOQ.
 */
package com.ogoma.marketing.infrastructure.jooq.tables.records;


import com.ogoma.marketing.infrastructure.jooq.tables.CampaignAudience;

import java.util.UUID;

import org.jooq.Record2;
import org.jooq.impl.UpdatableRecordImpl;


/**
 * This class is generated by jOOQ.
 */
@SuppressWarnings({ "all", "unchecked", "rawtypes", "this-escape" })
public class CampaignAudienceRecord extends UpdatableRecordImpl<CampaignAudienceRecord> {

    private static final long serialVersionUID = 1L;

    /**
     * Setter for <code>campaign_audience.campaign_id</code>.
     */
    public void setCampaignId(UUID value) {
        set(0, value);
    }

    /**
     * Getter for <code>campaign_audience.campaign_id</code>.
     */
    public UUID getCampaignId() {
        return (UUID) get(0);
    }

    /**
     * Setter for <code>campaign_audience.audience_id</code>.
     */
    public void setAudienceId(UUID value) {
        set(1, value);
    }

    /**
     * Getter for <code>campaign_audience.audience_id</code>.
     */
    public UUID getAudienceId() {
        return (UUID) get(1);
    }

    // -------------------------------------------------------------------------
    // Primary key information
    // -------------------------------------------------------------------------

    @Override
    public Record2<UUID, UUID> key() {
        return (Record2) super.key();
    }

    // -------------------------------------------------------------------------
    // Constructors
    // -------------------------------------------------------------------------

    /**
     * Create a detached CampaignAudienceRecord
     */
    public CampaignAudienceRecord() {
        super(CampaignAudience.CAMPAIGN_AUDIENCE);
    }

    /**
     * Create a detached, initialised CampaignAudienceRecord
     */
    public CampaignAudienceRecord(UUID campaignId, UUID audienceId) {
        super(CampaignAudience.CAMPAIGN_AUDIENCE);

        setCampaignId(campaignId);
        setAudienceId(audienceId);
        resetTouchedOnNotNull();
    }
}
