/*
 * This file is generated by jOOQ.
 */
package com.ogoma.marketing.infrastructure.jooq.tables.records;


import com.ogoma.marketing.infrastructure.jooq.tables.ContactAttributeValues;

import java.util.UUID;

import org.jooq.Record3;
import org.jooq.impl.UpdatableRecordImpl;


/**
 * This class is generated by jOOQ.
 */
@SuppressWarnings({ "all", "unchecked", "rawtypes", "this-escape" })
public class ContactAttributeValuesRecord extends UpdatableRecordImpl<ContactAttributeValuesRecord> {

    private static final long serialVersionUID = 1L;

    /**
     * Setter for <code>contact_attribute_values.contact_id</code>.
     */
    public void setContactId(UUID value) {
        set(0, value);
    }

    /**
     * Getter for <code>contact_attribute_values.contact_id</code>.
     */
    public UUID getContactId() {
        return (UUID) get(0);
    }

    /**
     * Setter for <code>contact_attribute_values.attribute</code>.
     */
    public void setAttribute(String value) {
        set(1, value);
    }

    /**
     * Getter for <code>contact_attribute_values.attribute</code>.
     */
    public String getAttribute() {
        return (String) get(1);
    }

    /**
     * Setter for <code>contact_attribute_values.value</code>.
     */
    public void setValue(String value) {
        set(2, value);
    }

    /**
     * Getter for <code>contact_attribute_values.value</code>.
     */
    public String getValue() {
        return (String) get(2);
    }

    // -------------------------------------------------------------------------
    // Primary key information
    // -------------------------------------------------------------------------

    @Override
    public Record3<UUID, String, String> key() {
        return (Record3) super.key();
    }

    // -------------------------------------------------------------------------
    // Constructors
    // -------------------------------------------------------------------------

    /**
     * Create a detached ContactAttributeValuesRecord
     */
    public ContactAttributeValuesRecord() {
        super(ContactAttributeValues.CONTACT_ATTRIBUTE_VALUES);
    }

    /**
     * Create a detached, initialised ContactAttributeValuesRecord
     */
    public ContactAttributeValuesRecord(UUID contactId, String attribute, String value) {
        super(ContactAttributeValues.CONTACT_ATTRIBUTE_VALUES);

        setContactId(contactId);
        setAttribute(attribute);
        setValue(value);
        resetTouchedOnNotNull();
    }
}
