/*
 * This file is generated by jOOQ.
 */
package com.ogoma.marketing.infrastructure.jooq.tables.records;


import com.ogoma.marketing.infrastructure.jooq.tables.Contacts;
import org.jooq.JSONB;
import org.jooq.Record1;
import org.jooq.impl.UpdatableRecordImpl;

import java.time.OffsetDateTime;
import java.util.UUID;


/**
 * This class is generated by jOOQ.
 */
@SuppressWarnings({ "all", "unchecked", "rawtypes", "this-escape" })
public class ContactsRecord extends UpdatableRecordImpl<ContactsRecord> {

    private static final long serialVersionUID = 1L;

    /**
     * Setter for <code>contacts.id</code>.
     */
    public void setId(UUID value) {
        set(0, value);
    }

    /**
     * Getter for <code>contacts.id</code>.
     */
    public UUID getId() {
        return (UUID) get(0);
    }

    /**
     * Setter for <code>contacts.first_name</code>.
     */
    public void setFirstName(String value) {
        set(1, value);
    }

    /**
     * Getter for <code>contacts.first_name</code>.
     */
    public String getFirstName() {
        return (String) get(1);
    }

    /**
     * Setter for <code>contacts.last_name</code>.
     */
    public void setLastName(String value) {
        set(2, value);
    }

    /**
     * Getter for <code>contacts.last_name</code>.
     */
    public String getLastName() {
        return (String) get(2);
    }

    /**
     * Setter for <code>contacts.email</code>.
     */
    public void setEmail(String value) {
        set(3, value);
    }

    /**
     * Getter for <code>contacts.email</code>.
     */
    public String getEmail() {
        return (String) get(3);
    }

    /**
     * Setter for <code>contacts.created_at</code>.
     */
    public void setCreatedAt(OffsetDateTime value) {
        set(4, value);
    }

    /**
     * Getter for <code>contacts.created_at</code>.
     */
    public OffsetDateTime getCreatedAt() {
        return (OffsetDateTime) get(4);
    }

    /**
     * Setter for <code>contacts.version</code>.
     */
    public void setVersion(Long value) {
        set(5, value);
    }

    /**
     * Getter for <code>contacts.version</code>.
     */
    public Long getVersion() {
        return (Long) get(5);
    }

    /**
     * Setter for <code>contacts.attributtes</code>.
     */
    public void setAttributtes(JSONB value) {
        set(6, value);
    }

    /**
     * Getter for <code>contacts.attributtes</code>.
     */
    public JSONB getAttributtes() {
        return (JSONB) get(6);
    }

    /**
     * Setter for <code>contacts.created_by</code>.
     */
    public void setCreatedBy(String value) {
        set(7, value);
    }

    /**
     * Getter for <code>contacts.created_by</code>.
     */
    public String getCreatedBy() {
        return (String) get(7);
    }

    /**
     * Setter for <code>contacts.last_updated_at</code>.
     */
    public void setLastUpdatedAt(OffsetDateTime value) {
        set(8, value);
    }

    /**
     * Getter for <code>contacts.last_updated_at</code>.
     */
    public OffsetDateTime getLastUpdatedAt() {
        return (OffsetDateTime) get(8);
    }

    /**
     * Setter for <code>contacts.last_updated_by</code>.
     */
    public void setLastUpdatedBy(String value) {
        set(9, value);
    }

    /**
     * Getter for <code>contacts.last_updated_by</code>.
     */
    public String getLastUpdatedBy() {
        return (String) get(9);
    }

    /**
     * Setter for <code>contacts.phone_number</code>.
     */
    public void setPhoneNumber(String value) {
        set(10, value);
    }

    /**
     * Getter for <code>contacts.phone_number</code>.
     */
    public String getPhoneNumber() {
        return (String) get(10);
    }

    // -------------------------------------------------------------------------
    // Primary key information
    // -------------------------------------------------------------------------

    @Override
    public Record1<UUID> key() {
        return (Record1) super.key();
    }

    // -------------------------------------------------------------------------
    // Constructors
    // -------------------------------------------------------------------------

    /**
     * Create a detached ContactsRecord
     */
    public ContactsRecord() {
        super(Contacts.CONTACTS);
    }

    /**
     * Create a detached, initialised ContactsRecord
     */
    public ContactsRecord(UUID id, String firstName, String lastName, String email, OffsetDateTime createdAt, Long version, JSONB attributtes, String createdBy, OffsetDateTime lastUpdatedAt, String lastUpdatedBy, String phoneNumber) {
        super(Contacts.CONTACTS);

        setId(id);
        setFirstName(firstName);
        setLastName(lastName);
        setEmail(email);
        setCreatedAt(createdAt);
        setVersion(version);
        setAttributtes(attributtes);
        setCreatedBy(createdBy);
        setLastUpdatedAt(lastUpdatedAt);
        setLastUpdatedBy(lastUpdatedBy);
        setPhoneNumber(phoneNumber);
        resetTouchedOnNotNull();
    }
}
