/*
 * This file is generated by jOOQ.
 */
package com.ogoma.marketing.infrastructure.jooq.tables.records;


import com.ogoma.marketing.infrastructure.jooq.tables.EmailTemplates;

import java.time.OffsetDateTime;
import java.util.UUID;

import org.jooq.JSON;
import org.jooq.Record1;
import org.jooq.impl.UpdatableRecordImpl;


/**
 * This class is generated by jOOQ.
 */
@SuppressWarnings({ "all", "unchecked", "rawtypes", "this-escape" })
public class EmailTemplatesRecord extends UpdatableRecordImpl<EmailTemplatesRecord> {

    private static final long serialVersionUID = 1L;

    /**
     * Setter for <code>email_templates.id</code>.
     */
    public void setId(UUID value) {
        set(0, value);
    }

    /**
     * Getter for <code>email_templates.id</code>.
     */
    public UUID getId() {
        return (UUID) get(0);
    }

    /**
     * Setter for <code>email_templates.created_at</code>.
     */
    public void setCreatedAt(OffsetDateTime value) {
        set(1, value);
    }

    /**
     * Getter for <code>email_templates.created_at</code>.
     */
    public OffsetDateTime getCreatedAt() {
        return (OffsetDateTime) get(1);
    }

    /**
     * Setter for <code>email_templates.name</code>.
     */
    public void setName(String value) {
        set(2, value);
    }

    /**
     * Getter for <code>email_templates.name</code>.
     */
    public String getName() {
        return (String) get(2);
    }

    /**
     * Setter for <code>email_templates.updated_at</code>.
     */
    public void setUpdatedAt(OffsetDateTime value) {
        set(3, value);
    }

    /**
     * Getter for <code>email_templates.updated_at</code>.
     */
    public OffsetDateTime getUpdatedAt() {
        return (OffsetDateTime) get(3);
    }

    /**
     * Setter for <code>email_templates.email_template</code>.
     */
    public void setEmailTemplate(JSON value) {
        set(4, value);
    }

    /**
     * Getter for <code>email_templates.email_template</code>.
     */
    public JSON getEmailTemplate() {
        return (JSON) get(4);
    }

    /**
     * Setter for <code>email_templates.version</code>.
     */
    public void setVersion(Long value) {
        set(5, value);
    }

    /**
     * Getter for <code>email_templates.version</code>.
     */
    public Long getVersion() {
        return (Long) get(5);
    }

    /**
     * Setter for <code>email_templates.created_by</code>.
     */
    public void setCreatedBy(String value) {
        set(6, value);
    }

    /**
     * Getter for <code>email_templates.created_by</code>.
     */
    public String getCreatedBy() {
        return (String) get(6);
    }

    /**
     * Setter for <code>email_templates.last_updated_by</code>.
     */
    public void setLastUpdatedBy(String value) {
        set(7, value);
    }

    /**
     * Getter for <code>email_templates.last_updated_by</code>.
     */
    public String getLastUpdatedBy() {
        return (String) get(7);
    }

    // -------------------------------------------------------------------------
    // Primary key information
    // -------------------------------------------------------------------------

    @Override
    public Record1<UUID> key() {
        return (Record1) super.key();
    }

    // -------------------------------------------------------------------------
    // Constructors
    // -------------------------------------------------------------------------

    /**
     * Create a detached EmailTemplatesRecord
     */
    public EmailTemplatesRecord() {
        super(EmailTemplates.EMAIL_TEMPLATES);
    }

    /**
     * Create a detached, initialised EmailTemplatesRecord
     */
    public EmailTemplatesRecord(UUID id, OffsetDateTime createdAt, String name, OffsetDateTime updatedAt, JSON emailTemplate, Long version, String createdBy, String lastUpdatedBy) {
        super(EmailTemplates.EMAIL_TEMPLATES);

        setId(id);
        setCreatedAt(createdAt);
        setName(name);
        setUpdatedAt(updatedAt);
        setEmailTemplate(emailTemplate);
        setVersion(version);
        setCreatedBy(createdBy);
        setLastUpdatedBy(lastUpdatedBy);
        resetTouchedOnNotNull();
    }
}
