/*
 * This file is generated by jOOQ.
 */
package com.ogoma.marketing.infrastructure.jooq.tables.records;


import com.ogoma.marketing.infrastructure.jooq.tables.MessageOutbox;

import java.time.OffsetDateTime;
import java.util.UUID;

import org.jooq.JSONB;
import org.jooq.Record1;
import org.jooq.impl.UpdatableRecordImpl;


/**
 * This class is generated by jOOQ.
 */
@SuppressWarnings({ "all", "unchecked", "rawtypes", "this-escape" })
public class MessageOutboxRecord extends UpdatableRecordImpl<MessageOutboxRecord> {

    private static final long serialVersionUID = 1L;

    /**
     * Setter for <code>message_outbox.id</code>.
     */
    public void setId(UUID value) {
        set(0, value);
    }

    /**
     * Getter for <code>message_outbox.id</code>.
     */
    public UUID getId() {
        return (UUID) get(0);
    }

    /**
     * Setter for <code>message_outbox.aggregate_type</code>.
     */
    public void setAggregateType(String value) {
        set(1, value);
    }

    /**
     * Getter for <code>message_outbox.aggregate_type</code>.
     */
    public String getAggregateType() {
        return (String) get(1);
    }

    /**
     * Setter for <code>message_outbox.aggregate_id</code>.
     */
    public void setAggregateId(UUID value) {
        set(2, value);
    }

    /**
     * Getter for <code>message_outbox.aggregate_id</code>.
     */
    public UUID getAggregateId() {
        return (UUID) get(2);
    }

    /**
     * Setter for <code>message_outbox.event_type</code>.
     */
    public void setEventType(String value) {
        set(3, value);
    }

    /**
     * Getter for <code>message_outbox.event_type</code>.
     */
    public String getEventType() {
        return (String) get(3);
    }

    /**
     * Setter for <code>message_outbox.event_version</code>.
     */
    public void setEventVersion(String value) {
        set(4, value);
    }

    /**
     * Getter for <code>message_outbox.event_version</code>.
     */
    public String getEventVersion() {
        return (String) get(4);
    }

    /**
     * Setter for <code>message_outbox.event_name</code>.
     */
    public void setEventName(String value) {
        set(5, value);
    }

    /**
     * Getter for <code>message_outbox.event_name</code>.
     */
    public String getEventName() {
        return (String) get(5);
    }

    /**
     * Setter for <code>message_outbox.payload</code>.
     */
    public void setPayload(JSONB value) {
        set(6, value);
    }

    /**
     * Getter for <code>message_outbox.payload</code>.
     */
    public JSONB getPayload() {
        return (JSONB) get(6);
    }

    /**
     * Setter for <code>message_outbox.created_at</code>.
     */
    public void setCreatedAt(OffsetDateTime value) {
        set(7, value);
    }

    /**
     * Getter for <code>message_outbox.created_at</code>.
     */
    public OffsetDateTime getCreatedAt() {
        return (OffsetDateTime) get(7);
    }

    /**
     * Setter for <code>message_outbox.processed</code>.
     */
    public void setProcessed(Boolean value) {
        set(8, value);
    }

    /**
     * Getter for <code>message_outbox.processed</code>.
     */
    public Boolean getProcessed() {
        return (Boolean) get(8);
    }

    /**
     * Setter for <code>message_outbox.processed_at</code>.
     */
    public void setProcessedAt(OffsetDateTime value) {
        set(9, value);
    }

    /**
     * Getter for <code>message_outbox.processed_at</code>.
     */
    public OffsetDateTime getProcessedAt() {
        return (OffsetDateTime) get(9);
    }

    /**
     * Setter for <code>message_outbox.version</code>.
     */
    public void setVersion(Long value) {
        set(10, value);
    }

    /**
     * Getter for <code>message_outbox.version</code>.
     */
    public Long getVersion() {
        return (Long) get(10);
    }

    // -------------------------------------------------------------------------
    // Primary key information
    // -------------------------------------------------------------------------

    @Override
    public Record1<UUID> key() {
        return (Record1) super.key();
    }

    // -------------------------------------------------------------------------
    // Constructors
    // -------------------------------------------------------------------------

    /**
     * Create a detached MessageOutboxRecord
     */
    public MessageOutboxRecord() {
        super(MessageOutbox.MESSAGE_OUTBOX);
    }

    /**
     * Create a detached, initialised MessageOutboxRecord
     */
    public MessageOutboxRecord(UUID id, String aggregateType, UUID aggregateId, String eventType, String eventVersion, String eventName, JSONB payload, OffsetDateTime createdAt, Boolean processed, OffsetDateTime processedAt, Long version) {
        super(MessageOutbox.MESSAGE_OUTBOX);

        setId(id);
        setAggregateType(aggregateType);
        setAggregateId(aggregateId);
        setEventType(eventType);
        setEventVersion(eventVersion);
        setEventName(eventName);
        setPayload(payload);
        setCreatedAt(createdAt);
        setProcessed(processed);
        setProcessedAt(processedAt);
        setVersion(version);
        resetTouchedOnNotNull();
    }
}
