/*
 * This file is generated by jOOQ.
 */
package com.ogoma.marketing.infrastructure.jooq.tables.records;


import com.ogoma.marketing.infrastructure.jooq.tables.Segments;

import java.time.OffsetDateTime;
import java.util.UUID;

import org.jooq.JSONB;
import org.jooq.Record1;
import org.jooq.impl.UpdatableRecordImpl;


/**
 * This class is generated by jOOQ.
 */
@SuppressWarnings({ "all", "unchecked", "rawtypes", "this-escape" })
public class SegmentsRecord extends UpdatableRecordImpl<SegmentsRecord> {

    private static final long serialVersionUID = 1L;

    /**
     * Setter for <code>segments.id</code>.
     */
    public void setId(UUID value) {
        set(0, value);
    }

    /**
     * Getter for <code>segments.id</code>.
     */
    public UUID getId() {
        return (UUID) get(0);
    }

    /**
     * Setter for <code>segments.name</code>.
     */
    public void setName(String value) {
        set(1, value);
    }

    /**
     * Getter for <code>segments.name</code>.
     */
    public String getName() {
        return (String) get(1);
    }

    /**
     * Setter for <code>segments.ruleset</code>.
     */
    public void setRuleset(JSONB value) {
        set(2, value);
    }

    /**
     * Getter for <code>segments.ruleset</code>.
     */
    public JSONB getRuleset() {
        return (JSONB) get(2);
    }

    /**
     * Setter for <code>segments.created_at</code>.
     */
    public void setCreatedAt(OffsetDateTime value) {
        set(3, value);
    }

    /**
     * Getter for <code>segments.created_at</code>.
     */
    public OffsetDateTime getCreatedAt() {
        return (OffsetDateTime) get(3);
    }

    /**
     * Setter for <code>segments.created_by</code>.
     */
    public void setCreatedBy(String value) {
        set(4, value);
    }

    /**
     * Getter for <code>segments.created_by</code>.
     */
    public String getCreatedBy() {
        return (String) get(4);
    }

    /**
     * Setter for <code>segments.last_updated_at</code>.
     */
    public void setLastUpdatedAt(OffsetDateTime value) {
        set(5, value);
    }

    /**
     * Getter for <code>segments.last_updated_at</code>.
     */
    public OffsetDateTime getLastUpdatedAt() {
        return (OffsetDateTime) get(5);
    }

    /**
     * Setter for <code>segments.last_updated_by</code>.
     */
    public void setLastUpdatedBy(String value) {
        set(6, value);
    }

    /**
     * Getter for <code>segments.last_updated_by</code>.
     */
    public String getLastUpdatedBy() {
        return (String) get(6);
    }

    /**
     * Setter for <code>segments.version</code>.
     */
    public void setVersion(Long value) {
        set(7, value);
    }

    /**
     * Getter for <code>segments.version</code>.
     */
    public Long getVersion() {
        return (Long) get(7);
    }

    /**
     * Setter for <code>segments.description</code>.
     */
    public void setDescription(String value) {
        set(8, value);
    }

    /**
     * Getter for <code>segments.description</code>.
     */
    public String getDescription() {
        return (String) get(8);
    }

    // -------------------------------------------------------------------------
    // Primary key information
    // -------------------------------------------------------------------------

    @Override
    public Record1<UUID> key() {
        return (Record1) super.key();
    }

    // -------------------------------------------------------------------------
    // Constructors
    // -------------------------------------------------------------------------

    /**
     * Create a detached SegmentsRecord
     */
    public SegmentsRecord() {
        super(Segments.SEGMENTS);
    }

    /**
     * Create a detached, initialised SegmentsRecord
     */
    public SegmentsRecord(UUID id, String name, JSONB ruleset, OffsetDateTime createdAt, String createdBy, OffsetDateTime lastUpdatedAt, String lastUpdatedBy, Long version, String description) {
        super(Segments.SEGMENTS);

        setId(id);
        setName(name);
        setRuleset(ruleset);
        setCreatedAt(createdAt);
        setCreatedBy(createdBy);
        setLastUpdatedAt(lastUpdatedAt);
        setLastUpdatedBy(lastUpdatedBy);
        setVersion(version);
        setDescription(description);
        resetTouchedOnNotNull();
    }
}
