/*
 * This file is generated by jOOQ.
 */
package com.ogoma.marketing.infrastructure.jooq.tables.records;


import com.ogoma.marketing.infrastructure.jooq.tables.SmsTemplates;

import java.time.OffsetDateTime;
import java.util.UUID;

import org.jooq.Record1;
import org.jooq.impl.UpdatableRecordImpl;


/**
 * This class is generated by jOOQ.
 */
@SuppressWarnings({ "all", "unchecked", "rawtypes", "this-escape" })
public class SmsTemplatesRecord extends UpdatableRecordImpl<SmsTemplatesRecord> {

    private static final long serialVersionUID = 1L;

    /**
     * Setter for <code>sms_templates.id</code>.
     */
    public void setId(UUID value) {
        set(0, value);
    }

    /**
     * Getter for <code>sms_templates.id</code>.
     */
    public UUID getId() {
        return (UUID) get(0);
    }

    /**
     * Setter for <code>sms_templates.content</code>.
     */
    public void setContent(String value) {
        set(1, value);
    }

    /**
     * Getter for <code>sms_templates.content</code>.
     */
    public String getContent() {
        return (String) get(1);
    }

    /**
     * Setter for <code>sms_templates.name</code>.
     */
    public void setName(String value) {
        set(2, value);
    }

    /**
     * Getter for <code>sms_templates.name</code>.
     */
    public String getName() {
        return (String) get(2);
    }

    /**
     * Setter for <code>sms_templates.version</code>.
     */
    public void setVersion(Long value) {
        set(3, value);
    }

    /**
     * Getter for <code>sms_templates.version</code>.
     */
    public Long getVersion() {
        return (Long) get(3);
    }

    /**
     * Setter for <code>sms_templates.description</code>.
     */
    public void setDescription(String value) {
        set(4, value);
    }

    /**
     * Getter for <code>sms_templates.description</code>.
     */
    public String getDescription() {
        return (String) get(4);
    }

    /**
     * Setter for <code>sms_templates.created_at</code>.
     */
    public void setCreatedAt(OffsetDateTime value) {
        set(5, value);
    }

    /**
     * Getter for <code>sms_templates.created_at</code>.
     */
    public OffsetDateTime getCreatedAt() {
        return (OffsetDateTime) get(5);
    }

    /**
     * Setter for <code>sms_templates.updated_by</code>.
     */
    public void setUpdatedBy(String value) {
        set(6, value);
    }

    /**
     * Getter for <code>sms_templates.updated_by</code>.
     */
    public String getUpdatedBy() {
        return (String) get(6);
    }

    /**
     * Setter for <code>sms_templates.created_by</code>.
     */
    public void setCreatedBy(String value) {
        set(7, value);
    }

    /**
     * Getter for <code>sms_templates.created_by</code>.
     */
    public String getCreatedBy() {
        return (String) get(7);
    }

    /**
     * Setter for <code>sms_templates.updated_at</code>.
     */
    public void setUpdatedAt(OffsetDateTime value) {
        set(8, value);
    }

    /**
     * Getter for <code>sms_templates.updated_at</code>.
     */
    public OffsetDateTime getUpdatedAt() {
        return (OffsetDateTime) get(8);
    }

    // -------------------------------------------------------------------------
    // Primary key information
    // -------------------------------------------------------------------------

    @Override
    public Record1<UUID> key() {
        return (Record1) super.key();
    }

    // -------------------------------------------------------------------------
    // Constructors
    // -------------------------------------------------------------------------

    /**
     * Create a detached SmsTemplatesRecord
     */
    public SmsTemplatesRecord() {
        super(SmsTemplates.SMS_TEMPLATES);
    }

    /**
     * Create a detached, initialised SmsTemplatesRecord
     */
    public SmsTemplatesRecord(UUID id, String content, String name, Long version, String description, OffsetDateTime createdAt, String updatedBy, String createdBy, OffsetDateTime updatedAt) {
        super(SmsTemplates.SMS_TEMPLATES);

        setId(id);
        setContent(content);
        setName(name);
        setVersion(version);
        setDescription(description);
        setCreatedAt(createdAt);
        setUpdatedBy(updatedBy);
        setCreatedBy(createdBy);
        setUpdatedAt(updatedAt);
        resetTouchedOnNotNull();
    }
}
