server.port=7056
spring.application.name=api
spring.datasource.url=${DB_URL:jdbc:postgresql://localhost:5432/marketing?currentSchema=marketing_main}
spring.datasource.username=${DB_USERNAME:postgres}
spring.datasource.password=${DB_PASSWORD:secret}
spring.security.oauth2.resourceserver.jwt.issuer-uri=${ISSUER_URL:https://login.microsoftonline.com/f52dddb7-7c2d-4c97-ae6e-554447981765/v2.0}
spring.flyway.enabled=true
spring.flyway.baseline-on-migrate=true
#mail properities
spring.mail.protocol=${EMAIL_PROTOCOL:smtp}
spring.mail.properties.mail.smtp.starttls.enable=true
spring.mail.host=${EMAIL_HOST:127.0.0.1}
spring.mail.port=${EMAIL_PORT:1025}
spring.mail.username=${EMAIL_USERNAME:testuser@gmail.com}
spring.mail.properties.mail.smtp.from=${EMAIL_FROM_ADDRESS:rensoft@noreply.com}
spring.mail.password=${EMAIL_PASSWORD:testpwd}
#Temporal properties
marketing.temporal.address=${TEMPORAL_ADDRESS:127.0.0.1:7233}
marketing.temporal.namespace=default
marketing.temporal.message-sender-queue=marketing-message-sender-queue
#Swagger config
springdoc.swagger-ui.oauth.use-pkce-with-authorization-code-grant=true
springdoc.swagger-ui.oauth.use-basic-authentication-with-access-code-grant=false
springdoc.swagger-ui.oauth.scopes=${OAUTH_SCOPES:openid,profile,email,offline_access,api://8fc0db74-dc6b-4f43-92b5-de753a53d077/access_as_user}
server.max-http-request-header-size=32KB

logging.level.org.springframework.jdbc.core.JdbcTemplate=DEBUG
logging.level.org.springframework.jdbc.core.StatementCreatorUtils=TRACE





