# Disable Flyway migrations during the swagger generation phase
spring.flyway.enabled=false

# Enable Springdoc OpenAPI/Swagger endpoints if they are not enabled by default
springdoc.api-docs.enabled=true
springdoc.swagger-ui.enabled=true
spring.datasource.url=r2dbc:h2:mem:///testdb?DB_CLOSE_DELAY=-1&DB_CLOSE_ON_EXIT=FALSE
spring.r2dbc.username=sa
spring.r2dbc.password=sa