spring.application.name=campaigns-batch-processor
spring.datasource.url=${DB_URL:jdbc:postgresql://localhost:5432/marketing?currentSchema=marketing_main}
spring.datasource.username=${DB_USERNAME:postgres}
spring.datasource.password=${DB_PASSWORD:secret}
#Temporal properties


