server.port=3322
spring.application.name=campaigns-batch-processor
spring.datasource.url=${DB_URL:jdbc:postgresql://localhost:5432/marketing?currentSchema=marketing_main}
spring.datasource.username=${DB_USERNAME:postgres}
spring.datasource.password=${DB_PASSWORD:secret}
spring.batch.job.enabled=false
spring.batch.jdbc.initialize-schema=never
spring.main.web-application-type=none


#Temporal properties


