/*
 * This file is generated by jOOQ.
 */
package com.ogoma.marketing.infrastructure.jooq;


import com.ogoma.marketing.infrastructure.jooq.tables.AudienceMembership;
import com.ogoma.marketing.infrastructure.jooq.tables.Audiences;
import com.ogoma.marketing.infrastructure.jooq.tables.CampaignAudience;
import com.ogoma.marketing.infrastructure.jooq.tables.CampaignChannels;
import com.ogoma.marketing.infrastructure.jooq.tables.CampaignSegments;
import com.ogoma.marketing.infrastructure.jooq.tables.Campaigns;
import com.ogoma.marketing.infrastructure.jooq.tables.ContactAttributeValues;
import com.ogoma.marketing.infrastructure.jooq.tables.Contacts;
import com.ogoma.marketing.infrastructure.jooq.tables.EmailTemplates;
import com.ogoma.marketing.infrastructure.jooq.tables.FlywaySchemaHistory;
import com.ogoma.marketing.infrastructure.jooq.tables.MessageOutbox;
import com.ogoma.marketing.infrastructure.jooq.tables.Segments;
import com.ogoma.marketing.infrastructure.jooq.tables.Shedlock;
import com.ogoma.marketing.infrastructure.jooq.tables.SmsTemplates;
import com.ogoma.marketing.infrastructure.jooq.tables.Users;

import java.util.Arrays;
import java.util.List;

import org.jooq.Catalog;
import org.jooq.Table;
import org.jooq.impl.DSL;
import org.jooq.impl.SchemaImpl;


/**
 * This class is generated by jOOQ.
 */
@SuppressWarnings({ "all", "unchecked", "rawtypes", "this-escape" })
public class DefaultSchema extends SchemaImpl {

    private static final long serialVersionUID = 1L;

    /**
     * The reference instance of <code>DEFAULT_SCHEMA</code>
     */
    public static final DefaultSchema DEFAULT_SCHEMA = new DefaultSchema();

    /**
     * The table <code>audience_membership</code>.
     */
    public final AudienceMembership AUDIENCE_MEMBERSHIP = AudienceMembership.AUDIENCE_MEMBERSHIP;

    /**
     * The table <code>audiences</code>.
     */
    public final Audiences AUDIENCES = Audiences.AUDIENCES;

    /**
     * The table <code>campaign_audience</code>.
     */
    public final CampaignAudience CAMPAIGN_AUDIENCE = CampaignAudience.CAMPAIGN_AUDIENCE;

    /**
     * The table <code>campaign_channels</code>.
     */
    public final CampaignChannels CAMPAIGN_CHANNELS = CampaignChannels.CAMPAIGN_CHANNELS;

    /**
     * The table <code>campaign_segments</code>.
     */
    public final CampaignSegments CAMPAIGN_SEGMENTS = CampaignSegments.CAMPAIGN_SEGMENTS;

    /**
     * The table <code>campaigns</code>.
     */
    public final Campaigns CAMPAIGNS = Campaigns.CAMPAIGNS;

    /**
     * The table <code>contact_attribute_values</code>.
     */
    public final ContactAttributeValues CONTACT_ATTRIBUTE_VALUES = ContactAttributeValues.CONTACT_ATTRIBUTE_VALUES;

    /**
     * The table <code>contacts</code>.
     */
    public final Contacts CONTACTS = Contacts.CONTACTS;

    /**
     * The table <code>email_templates</code>.
     */
    public final EmailTemplates EMAIL_TEMPLATES = EmailTemplates.EMAIL_TEMPLATES;

    /**
     * The table <code>flyway_schema_history</code>.
     */
    public final FlywaySchemaHistory FLYWAY_SCHEMA_HISTORY = FlywaySchemaHistory.FLYWAY_SCHEMA_HISTORY;

    /**
     * The table <code>message_outbox</code>.
     */
    public final MessageOutbox MESSAGE_OUTBOX = MessageOutbox.MESSAGE_OUTBOX;

    /**
     * The table <code>segments</code>.
     */
    public final Segments SEGMENTS = Segments.SEGMENTS;

    /**
     * The table <code>shedlock</code>.
     */
    public final Shedlock SHEDLOCK = Shedlock.SHEDLOCK;

    /**
     * The table <code>sms_templates</code>.
     */
    public final SmsTemplates SMS_TEMPLATES = SmsTemplates.SMS_TEMPLATES;

    /**
     * The table <code>users</code>.
     */
    public final Users USERS = Users.USERS;

    /**
     * No further instances allowed
     */
    private DefaultSchema() {
        super(DSL.name(""), null, DSL.comment(""));
    }


    @Override
    public Catalog getCatalog() {
        return DefaultCatalog.DEFAULT_CATALOG;
    }

    @Override
    public final List<Table<?>> getTables() {
        return Arrays.asList(
            AudienceMembership.AUDIENCE_MEMBERSHIP,
            Audiences.AUDIENCES,
            CampaignAudience.CAMPAIGN_AUDIENCE,
            CampaignChannels.CAMPAIGN_CHANNELS,
            CampaignSegments.CAMPAIGN_SEGMENTS,
            Campaigns.CAMPAIGNS,
            ContactAttributeValues.CONTACT_ATTRIBUTE_VALUES,
            Contacts.CONTACTS,
            EmailTemplates.EMAIL_TEMPLATES,
            FlywaySchemaHistory.FLYWAY_SCHEMA_HISTORY,
            MessageOutbox.MESSAGE_OUTBOX,
            Segments.SEGMENTS,
            Shedlock.SHEDLOCK,
            SmsTemplates.SMS_TEMPLATES,
            Users.USERS
        );
    }
}
