/*
 * This file is generated by jOOQ.
 */
package com.ogoma.marketing.infrastructure.jooq;


import com.ogoma.marketing.infrastructure.jooq.tables.*;
import com.ogoma.marketing.infrastructure.jooq.tables.records.*;
import org.jooq.ForeignKey;
import org.jooq.TableField;
import org.jooq.UniqueKey;
import org.jooq.impl.DSL;
import org.jooq.impl.Internal;
import org.jooq.impl.QOM.ForeignKeyRule;


/**
 * A class modelling foreign key relationships and constraints of tables in the
 * default schema.
 */
@SuppressWarnings({ "all", "unchecked", "rawtypes", "this-escape" })
public class Keys {

    // -------------------------------------------------------------------------
    // UNIQUE and PRIMARY KEY definitions
    // -------------------------------------------------------------------------

    public static final UniqueKey<AudienceMembershipRecord> AUDIENCE_MEMBERSHIP_PKEY = Internal.createUniqueKey(AudienceMembership.AUDIENCE_MEMBERSHIP, DSL.name("audience_membership_pkey"), new TableField[] { AudienceMembership.AUDIENCE_MEMBERSHIP.ID }, true);
    public static final UniqueKey<AudiencesRecord> AUDIENCES_PKEY = Internal.createUniqueKey(Audiences.AUDIENCES, DSL.name("audiences_pkey"), new TableField[] { Audiences.AUDIENCES.ID }, true);
    public static final UniqueKey<CampaignAudienceRecord> CAMPAIGN_AUDIENCE_PKEY = Internal.createUniqueKey(CampaignAudience.CAMPAIGN_AUDIENCE, DSL.name("campaign_audience_pkey"), new TableField[] { CampaignAudience.CAMPAIGN_AUDIENCE.CAMPAIGN_ID, CampaignAudience.CAMPAIGN_AUDIENCE.AUDIENCE_ID }, true);
    public static final UniqueKey<CampaignChannelsRecord> CAMPAIGN_CHANNELS_PKEY = Internal.createUniqueKey(CampaignChannels.CAMPAIGN_CHANNELS, DSL.name("campaign_channels_pkey"), new TableField[] { CampaignChannels.CAMPAIGN_CHANNELS.CAMPAIGN_ID, CampaignChannels.CAMPAIGN_CHANNELS.CHANNEL }, true);
    public static final UniqueKey<CampaignSegmentsRecord> CAMPAIGN_SEGMENTS_PKEY = Internal.createUniqueKey(CampaignSegments.CAMPAIGN_SEGMENTS, DSL.name("campaign_segments_pkey"), new TableField[] { CampaignSegments.CAMPAIGN_SEGMENTS.CAMPAIGN_ID, CampaignSegments.CAMPAIGN_SEGMENTS.SEGMENT_ID }, true);
    public static final UniqueKey<CampaignsRecord> CAMPAIGNS_PKEY = Internal.createUniqueKey(Campaigns.CAMPAIGNS, DSL.name("campaigns_pkey"), new TableField[] { Campaigns.CAMPAIGNS.ID }, true);
    public static final UniqueKey<ContactAttributeValuesRecord> CONTACT_ATTRIBUTE_VALUES_PKEY = Internal.createUniqueKey(ContactAttributeValues.CONTACT_ATTRIBUTE_VALUES, DSL.name("contact_attribute_values_pkey"), new TableField[] { ContactAttributeValues.CONTACT_ATTRIBUTE_VALUES.CONTACT_ID, ContactAttributeValues.CONTACT_ATTRIBUTE_VALUES.ATTRIBUTE, ContactAttributeValues.CONTACT_ATTRIBUTE_VALUES.VALUE }, true);
    public static final UniqueKey<ContactsRecord> CONTACTS_PKEY = Internal.createUniqueKey(Contacts.CONTACTS, DSL.name("contacts_pkey"), new TableField[] { Contacts.CONTACTS.ID }, true);
    public static final UniqueKey<EmailTemplatesRecord> EMAIL_TEMPLATES_PKEY = Internal.createUniqueKey(EmailTemplates.EMAIL_TEMPLATES, DSL.name("email_templates_pkey"), new TableField[] { EmailTemplates.EMAIL_TEMPLATES.ID }, true);
    public static final UniqueKey<FlywaySchemaHistoryRecord> FLYWAY_SCHEMA_HISTORY_PK = Internal.createUniqueKey(FlywaySchemaHistory.FLYWAY_SCHEMA_HISTORY, DSL.name("flyway_schema_history_pk"), new TableField[] { FlywaySchemaHistory.FLYWAY_SCHEMA_HISTORY.INSTALLED_RANK }, true);
    public static final UniqueKey<MessageOutboxRecord> MESSAGE_OUTBOX_PKEY = Internal.createUniqueKey(MessageOutbox.MESSAGE_OUTBOX, DSL.name("message_outbox_pkey"), new TableField[] { MessageOutbox.MESSAGE_OUTBOX.ID }, true);
    public static final UniqueKey<SegmentsRecord> SEGMENTS_PKEY = Internal.createUniqueKey(Segments.SEGMENTS, DSL.name("segments_pkey"), new TableField[] { Segments.SEGMENTS.ID }, true);
    public static final UniqueKey<ShedlockRecord> SHEDLOCK_PKEY = Internal.createUniqueKey(Shedlock.SHEDLOCK, DSL.name("shedlock_pkey"), new TableField[] { Shedlock.SHEDLOCK.NAME }, true);
    public static final UniqueKey<SmsTemplatesRecord> SMS_TEMPLATES_PKEY = Internal.createUniqueKey(SmsTemplates.SMS_TEMPLATES, DSL.name("sms_templates_pkey"), new TableField[] { SmsTemplates.SMS_TEMPLATES.ID }, true);
    public static final UniqueKey<UsersRecord> USERS_PKEY = Internal.createUniqueKey(Users.USERS, DSL.name("users_pkey"), new TableField[] { Users.USERS.ID }, true);

    // -------------------------------------------------------------------------
    // FOREIGN KEY definitions
    // -------------------------------------------------------------------------

    public static final ForeignKey<CampaignAudienceRecord, AudiencesRecord> CAMPAIGN_AUDIENCE__CAMPAIGN_AUDIENCE_AUDIENCE_ID_FKEY = Internal.createForeignKey(CampaignAudience.CAMPAIGN_AUDIENCE, DSL.name("campaign_audience_audience_id_fkey"), new TableField[] { CampaignAudience.CAMPAIGN_AUDIENCE.AUDIENCE_ID }, Keys.AUDIENCES_PKEY, new TableField[] { Audiences.AUDIENCES.ID }, true, ForeignKeyRule.NO_ACTION, ForeignKeyRule.NO_ACTION);
    public static final ForeignKey<CampaignAudienceRecord, CampaignsRecord> CAMPAIGN_AUDIENCE__CAMPAIGN_AUDIENCE_CAMPAIGN_ID_FKEY = Internal.createForeignKey(CampaignAudience.CAMPAIGN_AUDIENCE, DSL.name("campaign_audience_campaign_id_fkey"), new TableField[] { CampaignAudience.CAMPAIGN_AUDIENCE.CAMPAIGN_ID }, Keys.CAMPAIGNS_PKEY, new TableField[] { Campaigns.CAMPAIGNS.ID }, true, ForeignKeyRule.NO_ACTION, ForeignKeyRule.NO_ACTION);
    public static final ForeignKey<CampaignChannelsRecord, CampaignsRecord> CAMPAIGN_CHANNELS__CAMPAIGN_CHANNELS_CAMPAIGN_ID_FKEY = Internal.createForeignKey(CampaignChannels.CAMPAIGN_CHANNELS, DSL.name("campaign_channels_campaign_id_fkey"), new TableField[] { CampaignChannels.CAMPAIGN_CHANNELS.CAMPAIGN_ID }, Keys.CAMPAIGNS_PKEY, new TableField[] { Campaigns.CAMPAIGNS.ID }, true, ForeignKeyRule.NO_ACTION, ForeignKeyRule.NO_ACTION);
    public static final ForeignKey<CampaignSegmentsRecord, CampaignsRecord> CAMPAIGN_SEGMENTS__CAMPAIGN_SEGMENTS_CAMPAIGN_ID_FKEY = Internal.createForeignKey(CampaignSegments.CAMPAIGN_SEGMENTS, DSL.name("campaign_segments_campaign_id_fkey"), new TableField[] { CampaignSegments.CAMPAIGN_SEGMENTS.CAMPAIGN_ID }, Keys.CAMPAIGNS_PKEY, new TableField[] { Campaigns.CAMPAIGNS.ID }, true, ForeignKeyRule.NO_ACTION, ForeignKeyRule.NO_ACTION);
    public static final ForeignKey<CampaignSegmentsRecord, SegmentsRecord> CAMPAIGN_SEGMENTS__CAMPAIGN_SEGMENTS_SEGMENT_ID_FKEY = Internal.createForeignKey(CampaignSegments.CAMPAIGN_SEGMENTS, DSL.name("campaign_segments_segment_id_fkey"), new TableField[] { CampaignSegments.CAMPAIGN_SEGMENTS.SEGMENT_ID }, Keys.SEGMENTS_PKEY, new TableField[] { Segments.SEGMENTS.ID }, true, ForeignKeyRule.NO_ACTION, ForeignKeyRule.NO_ACTION);
    public static final ForeignKey<ContactAttributeValuesRecord, ContactsRecord> CONTACT_ATTRIBUTE_VALUES__CONTACT_ATTRIBUTE_VALUES_CONTACT_ID_FKEY = Internal.createForeignKey(ContactAttributeValues.CONTACT_ATTRIBUTE_VALUES, DSL.name("contact_attribute_values_contact_id_fkey"), new TableField[] { ContactAttributeValues.CONTACT_ATTRIBUTE_VALUES.CONTACT_ID }, Keys.CONTACTS_PKEY, new TableField[] { Contacts.CONTACTS.ID }, true, ForeignKeyRule.NO_ACTION, ForeignKeyRule.NO_ACTION);
}
