/*
 * This file is generated by jOOQ.
 */
package com.ogoma.marketing.infrastructure.jooq;


import com.ogoma.marketing.infrastructure.jooq.tables.*;


/**
 * Convenience access to all tables in the default schema.
 */
@SuppressWarnings({ "all", "unchecked", "rawtypes", "this-escape" })
public class Tables {

    /**
     * The table <code>audience_membership</code>.
     */
    public static final AudienceMembership AUDIENCE_MEMBERSHIP = AudienceMembership.AUDIENCE_MEMBERSHIP;

    /**
     * The table <code>audiences</code>.
     */
    public static final Audiences AUDIENCES = Audiences.AUDIENCES;

    /**
     * The table <code>campaign_audience</code>.
     */
    public static final CampaignAudience CAMPAIGN_AUDIENCE = CampaignAudience.CAMPAIGN_AUDIENCE;

    /**
     * The table <code>campaign_channels</code>.
     */
    public static final CampaignChannels CAMPAIGN_CHANNELS = CampaignChannels.CAMPAIGN_CHANNELS;

    /**
     * The table <code>campaign_segments</code>.
     */
    public static final CampaignSegments CAMPAIGN_SEGMENTS = CampaignSegments.CAMPAIGN_SEGMENTS;

    /**
     * The table <code>campaigns</code>.
     */
    public static final Campaigns CAMPAIGNS = Campaigns.CAMPAIGNS;

    /**
     * The table <code>contact_attribute_values</code>.
     */
    public static final ContactAttributeValues CONTACT_ATTRIBUTE_VALUES = ContactAttributeValues.CONTACT_ATTRIBUTE_VALUES;

    /**
     * The table <code>contacts</code>.
     */
    public static final Contacts CONTACTS = Contacts.CONTACTS;

    /**
     * The table <code>email_templates</code>.
     */
    public static final EmailTemplates EMAIL_TEMPLATES = EmailTemplates.EMAIL_TEMPLATES;

    /**
     * The table <code>flyway_schema_history</code>.
     */
    public static final FlywaySchemaHistory FLYWAY_SCHEMA_HISTORY = FlywaySchemaHistory.FLYWAY_SCHEMA_HISTORY;

    /**
     * The table <code>message_outbox</code>.
     */
    public static final MessageOutbox MESSAGE_OUTBOX = MessageOutbox.MESSAGE_OUTBOX;

    /**
     * The table <code>segments</code>.
     */
    public static final Segments SEGMENTS = Segments.SEGMENTS;

    /**
     * The table <code>shedlock</code>.
     */
    public static final Shedlock SHEDLOCK = Shedlock.SHEDLOCK;

    /**
     * The table <code>sms_templates</code>.
     */
    public static final SmsTemplates SMS_TEMPLATES = SmsTemplates.SMS_TEMPLATES;

    /**
     * The table <code>users</code>.
     */
    public static final Users USERS = Users.USERS;
}
