spring.application.name=transacation-message-sender
server.port=7990
spring.datasource.url=jdbc:postgresql://${DB_URL:localhost:5432/marketing?currentSchema=marketing_main}
spring.datasource.username=${DB_USERNAME:postgres}
spring.datasource.password=${DB_PASSWORD:secret}
spring.datasource.driver-class-name=org.postgresql.Driver
#mail properities
spring.mail.protocol=${EMAIL_PROTOCOL:smtp}
spring.mail.properties.mail.smtp.starttls.enable=true
spring.mail.host=${EMAIL_HOST:127.0.0.1}
spring.mail.port=${EMAIL_PORT:1025}
spring.mail.username=${EMAIL_USERNAME:testuser@gmail.com}
spring.mail.properties.mail.smtp.from=${EMAIL_FROM_ADDRESS:rensoft@noreply.com}
spring.mail.password=${EMAIL_PASSWORD:testpwd}
#Temporal properties
marketing.temporal.address=127.0.0.1:7233
marketing.temporal.namespace=default
marketing.temporal.message-sender-queue=marketing-message-sender-queque
