name: Publish API Docs
on:
  push:
    branches:
      - main
permissions:
  contents: write
jobs:
  docs:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - uses: actions/setup-java@v4
        with:
          distribution: temurin
          java-version: 26
      - run: ./mvnw clean verify
        env:
          SPRING_PROFILES_ACTIVE: "swagger"
      - run: |
          mkdir -p docs
          cp api/target/generated-docs/swagger-ui/openapi.yaml docs/
      - name: Generate Swagger UI
        uses: Legion2/swagger-ui-action@v1
        with:
          output: ./docs
          spec-file: openapi.yaml
          version: 5.x
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
      - uses: peaceiris/actions-gh-pages@v4
        with:
          github_token: ${{ secrets.GITHUB_TOKEN }}
          publish_dir: ./docs